### ISSUE TITLE
pylontech and daly smart bms different soc

### ISSUE THREAD

**Issue by Micha854** [Louisvdw/dbus-serialbattery#1027]
### Describe the problem

Hello,

We have a pylontech 9.6kw battery and a DIY with 9.6kw and daly bms

Both batteries are summarized using the “Battery Aggregator” from @pulquero

Final charging voltage is 51.80V and trickle voltage is then 50.60V

This means that the pylontech has a soc of 93% and the Daly has 99.1%

is discharged up to 30% (ESS) so pylontech is around 24-25% and the daly is at 35-36%

So we have a difference of about 10% in the lower SOC range

In the serial driver we set the Soc calculation to true but we didn't notice any difference.

what can we do?

### Driver version

v1.0.20230531

### Venus OS device type

Raspberry Pi

### Venus OS version

3.30

### BMS type

Daly Smart BMS

### Cell count

15

### Battery count

2

### Connection type

Serial USB adapter to RS485

### Config file

```ini
default config with soc calculation true
```

### Relevant log output

```shell
no mean
```

**Comment by mr-manuel** [comment]
Reading the notes when opening a new issue would help :-)

Please also read the changelog.

Anyway, what are you hoping to achieve with the SOC calculation?
