### ISSUE TITLE
SOC Reset with 3 Battery Banks

### ISSUE THREAD

**Issue by rolandlueders** [Louisvdw/dbus-serialbattery#1032]
### Describe the bug

I don´t use the SOC Reset feature but i want to use it to balance from time to time. So I set the Cell_OVP to 3,55V and the CellOVPR to 3,45V , Balance_Trigger_Voltage to 0,005V and Start_Balance to 3,47V in the JK BMSes. The Voltage rises to more then MAX_CELL_VOLTAGE and when reaching 3,47V balancing beginns. When one cellvoltage rises to more of SOC_RESET_VOLTAGE the Charge Voltage will lowered. So thins Battery will balanced perfectly. But when the criteria of SOC_Reset are reeached, the Charge Voltage is too low for the other Batteries: The Cage_Current is low and the PV-Voltage is more than MPP Voltage. Next Day in Parameters are different Charge modes displayed. It would be better, when the end of the SOC_Reset Mode is only reached if all connected Batteries are well balanced.
One Battery
![image](https://github.com/Louisvdw/dbus-serialbattery/assets/158720201/afd6dad3-09f2-40c4-91ef-7e4434aed1a1)
And another Battery:
![image](https://github.com/Louisvdw/dbus-serialbattery/assets/158720201/e056bfd3-f6dd-4366-9968-c3fdef377cbc)

### How to reproduce

.

### Expected behavior

All three Batteries should reach SOC_RESET_VOLTAGE in the same day if enough PV power ist available.

### Driver version

1.2.20240408

### Venus OS device type

Raspberry Pi 4

### Venus OS version

v330-18

### BMS type

JKBMS / Heltec BMS

### Cell count

8

### Battery count

3

### Connection type

Serial USB adapter to RS485

### Config file

```ini
MAX_BATTERY_CHARGE_CURRENT =150.0
 MAX_BATTERY_DISCHARGE_CURRENT =180.0
MAX_CELL_VOLTAGE   = 3.45
SOC_RESET_VOLTAGE = 3.50
SOC_RESET_AFTER_DAYS = 1
SOC_LEVEL_TO_RESET_VOLTAGE_LIMIT = 97
; Charge current control management enable (True/False).
CCCM_SOC_ENABLE = false
; Discharge current control management enable (True/False).
DCCM_SOC_ENABLE = false
CELL_VOLTAGES_WHILE_CHARGING   = 3.55, 3.50, 3.45, 3.30
MAX_CHARGE_CURRENT_CV_FRACTION =    0, 0.1,  0.3,    1
BMS_TYPE = Jkbms
```

### Relevant log output

```shell
.
```

**Comment by mr-manuel** [comment]
This is not an issue of this driver and was asked many times. You have to use a battery aggregator. https://github.com/Dr-Gigavolt/dbus-aggregate-batteries is the only one that I know of, where this should behave like you want.
