### ISSUE TITLE
#8 calculation error

### ISSUE THREAD

**Issue by ikorpershoek** [Louisvdw/dbus-serialbattery#1111]
### Describe the problem

After every cerbo reset this alarm is raised. 

### Driver version

Latest official release

### Venus OS device type

Cerbo GX

### Venus OS version

v350-13 / 3.41

### BMS type

JKBMS / Heltec BMS

### Cell count

8

### Battery count

1

### Connection type

Serial USB adapter to TTL

### Config file

```ini
standard config file
```

### Relevant log output

```shell
#8 Internal calculation error
```

**Comment by mr-manuel** [comment]
Unfortunately you did not read the instructions and did not orovide the needed informations. This way I cannot help you. Please try again to read what you have to provide and where you can find it

**Comment by ikorpershoek** [comment]
I'm sorry I tried to provide all the info as far as I understood the questions. It's a plain install of the driver no changes made. So I thought it was enough. I will reread the instructions.

**Comment by RichGorrod** [comment]
I have exactly the same issue. CheersRich. Rich Gorrod07768453552On 18 Aug 2024, at 06:11, ikorpershoek ***@***.***> wrote:﻿
I'm sorry I tried to provide all the info as far as I understood the questions. It's a plain install of the driver no changes made. So I thought it was enough. I will reread the instructions.

**Comment by mr-manuel** [comment]
@RichGorrod since this is a very general error message it's not very likely that you have exactly the same issue. Please read the docs.

**Comment by Becker884** [comment]
Just installed Venus 3,41 today with newest serialbatt stable - same problem here.
JK BMS over RS485 with 18x 280Ah cells.

**Comment by Becker884** [comment]
i tried v1.4 nighty:
`@4000000066c24bda1549d634 ERROR:SerialBattery:**CONFIG ISSUE**: Minimum value of CELL_VOLTAGES_WHILE_DISCHARGING (3.0 V) is higher than MIN_CELL_VOLTAGE (2.9 V). MIN_CELL_VOLTAGE will never be reached this way. Please check the configuration.`
I changed MIN_CELL_VOLTAGE to 3.000V -> no errors.

maybe this was the same problem in v1.3 ?

**Comment by Becker884** [comment]
After a new reboot again error #8 

![grafik](https://github.com/user-attachments/assets/a1156ba7-9c96-4805-a73f-c053b96db0ae)

**Comment by Becker884** [comment]
It´s random:
![grafik](https://github.com/user-attachments/assets/93df9e0a-f6dc-4d3a-a7b2-5152254901ad)
sometimes error #8 comes after reboot, sometimes not.
even with fresh installed serialbatt without any modification

**Comment by mr-manuel** [comment]
@Becker884 since this is a very general error message it's not very likely that you have exactly the same issue. Open a new issue for your problem.

**Comment by seamaster101** [comment]
I also have the same problem with all 4 of my batteries 
![IMG_5200](https://github.com/user-attachments/assets/27358d1c-5d1a-4da0-899f-87fca68b235d)

**Comment by mr-manuel** [comment]
Since no one of you read all the instructions and provided correct and needed informations I will close this issue. Please do so when opening a new issue.

**Comment by seamaster101** [comment]
Don’t be frustrated like that please! Keep the great work you guys have been doing.  What information specifically do you need?JordanOn Aug 21, 2024, at 05:25, Manuel ***@***.***> wrote:﻿
Since no one of you read all the instructions and provided correct and needed informations I will close this issue. Please do so when opening a new issue.
