### ISSUE TITLE
Support for 500kbps CAN bus connection

### ISSUE THREAD

**Issue by NickRoberts174** [Louisvdw/dbus-serialbattery#1135]
### Is your feature request related to a problem? Please describe.

After much trial error, trying to get the driver to communicate with my 2 batteries in parrallel, running Daly smart BMS's with WNT interface boards, I found a clue in Mr. Manuel's version that you have to select a 250kbps port (which the WNT boards don't support - they run on 500kbps), which was why the driver doesn't appear to work on CAN bus for me. 

![image](https://github.com/user-attachments/assets/191636cd-4ac1-4e54-a169-2a24807b0ab3)

![image](https://github.com/user-attachments/assets/e441b50f-38b1-478a-b2fa-4ce0e944a711)

### Describe the solution you'd like

Is there any way that the driver could be selected to work on 500kbps so that the Daly WNT boards are compatible please? 

### Describe alternatives you've considered

I have tried using 2x off  RS485 to USB serial adapters, one in each battery, but the driver will only work with one at a time. I have tried all ways of trouble shooting this and have had no success, I believe CAN bus would be the neatest solution as it removes the need for additional hardware which would become failure points of failure. Below are the combinations I have tried:

![image](https://github.com/user-attachments/assets/f8a57597-a13d-4edd-96f2-a24f1d157c5a)
![image](https://github.com/user-attachments/assets/c183410f-48b3-4cfa-8e08-8893558f046c)
![image](https://github.com/user-attachments/assets/aed7dd08-d20e-429f-b24a-6c74d3f448ae)
![image](https://github.com/user-attachments/assets/446f5573-f7b0-43b9-993e-4bbd4fff223a)
![image](https://github.com/user-attachments/assets/e9601901-f873-47cf-a5a2-07a7d6f539c9)
![image](https://github.com/user-attachments/assets/006b6438-883b-4d7a-b434-daa244ad5c15)

**Comment by mr-manuel** [comment]
If you found a clue in my version of the driver, please open a feature request in my repository.
