### ISSUE TITLE
Archiving this Repository and Redirecting Users to mr-manuel/venus-os_dbus-serialbattery

### ISSUE THREAD

**Issue by KoljaWindeler** [Louisvdw/dbus-serialbattery#1146]
### Describe the problem

Hey Louis,

First off, a huge thank you for all the hard work you put into the dbus-serialbattery project! The effort you put into getting things started was incredible, and it really made a difference for the community.

I understood you've moved on from the project, and it's great to see that @mr-manuel has picked it up and kept things going strong. The project has come a long way thanks to his dedication, and we all appreciate the ongoing work.

That said, there are still two repositories out there (yours and manuel's fork), which is causing some confusion. People are still opening issues here, but since there's no active response, manuel has been stepping in to help out.

It would be super helpful if you could archive this repo and update the README to point users to mr-manuel's fork. That way, everyone can be directed to the latest version, and it should help clear up any confusion.

Thanks again for everything you've done, and I hope this suggestion makes sense!

Best, Kolja

**Comment by mr-manuel** [comment]
Hello Louis,

Thank you so much for your incredible work on this project! I am thrilled to have discovered it and to have had the opportunity to contribute. Exciting updates are on the way, including an upgrade to `v2.0.0`. Without you this would never have been possible.

I have prepared the repository for archiving and opened a PR to update the README, see https://github.com/Louisvdw/dbus-serialbattery/pull/1148. The current text is just a placeholder, so please feel free to modify it as you see fit. Additionally, I have updated the documentation links.

Before archiving the repository, please remember to delete the `update-readme` branch.

Regards,
Manuel
