### ISSUE TITLE
Installing this driver destroys a already installed one

### ISSUE THREAD

**Issue by stundenblume** [Louisvdw/dbus-serialbattery#128]
1.: Thank you for this very helpful driver!

**Describe the bug**
Installing this driver destroys a already installed one.

**To Reproduce**
1. working [dbus-mqtt-devices](https://github.com/freakent/dbus-mqtt-devices) driver
2. installing this driver
3. reboot
4. dbus-mqtt-devices driver doesn't work anymore

**Expected behavior**
Installing this driver should not influence other drivers.

**Solution**
Reinstalling dbus-mqtt-devices helped

**What could I find**
Your installation script replaced a already existing entry in `/data/rc.local`
Reentering it did not help. I had to reinstall dbus-mqtt-devices

**Comment by Louisvdw** [comment]
This was a known issue for the autoinstaller that the VenusOS provides0. 
For serialbattery it will not be a major issue if the rc.local with it's commands don't exist anymore after installation, but then when you upgrade your VenusOS firmware next time you will have to install the driver again. 

The only way to get around this would be to not use the auto installer option, and then adjusting the ssh install script to not destroy any existing files.

**Comment by stundenblume** [comment]
@ngardiner
the setup script of dbus-mqtt-devices [appends](https://github.com/freakent/dbus-mqtt-devices/blob/main/bin/setup.sh#L33) his line to `/data/rc.local`

For me everything is working new. But just to be aware that this can happen.

**Comment by ngardiner** [comment]
> @ngardiner the setup script of dbus-mqtt-devices [appends](https://github.com/freakent/dbus-mqtt-devices/blob/main/bin/setup.sh#L33) his line to `/data/rc.local`
> 
> For me everything is working new. But just to be aware that this can happen.

That's going to work I'd nobody puts an exit 0 at the end of their script or runs any command which doesn't either fork or finish immediately, but we are at the point where people have to guess what other scripts are going to do.

**Comment by kr0815** [comment]
i found this old topic, have exactly the same problems
In rc-local there was en entry that reinstalled dbus-serialbattery at each reboot - at the reinstall deleted my other entries there

I uncommented that entry - now i want to change max charge / discharge current in utils.py, but this has no effect?
utils.py says 20A/20A , Venus GUI says 5A / 60A , very strange
Do i really need a reinstall each time the unit reboots?

**Comment by pos-ei-don** [comment]
Hm, sadly the installation deleted my rc.local without any backup. so i lost many settings.....

**Comment by Louisvdw** [comment]
Fixed in #370
