### ISSUE TITLE
very slow charging when MPPT Charger external controlled by the Daly BMS

### ISSUE THREAD

**Issue by Micha854** [Louisvdw/dbus-serialbattery#148]
**VenusOS (please complete the following information):**
 - Device type: Raspberry Pi
 - Venus OS Version 2.87

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: Daly
 - Cells: 8
 - Interface: USB-RS485

Hello Louis,

i use your serial battery driver. great thing thanks!
I have a problem that my lifepo4 only charges with 80 watts for hours... is a very slow charging

If I remove the RS485 connection to the raspberry, the mppt charge controller is no longer controlled externally and the charging power increases considerably.

settings of the parameters are:

CVL: 28.4V
CCL: 50A ( i see on my dashboard the value stand by 50A )
DCL: 100A

these are also the settings of my daly bms, i limited my end-of-charge voltage to 26.8V in the dvcc menu.

I can't explain where the problem is. do you have any idea?

**Comment by Louisvdw** [comment]
Hi @Micha854 
I suspect that the dynamic charge limit(CCCM) could be influencing it, or that there is an issue in the cells. 
CCCM should only have an impact when you get close to full SOC.
Can you look at the BMS Charge and Discharge Limits graph in the Advance section in your VRM. This will show what limits are used over a day time period. Also look at the BMS Min/Max Cell voltage and Battery Voltage and Current graphs. These should show if there is a setting issue or something with a cell or battery. Keep the period on Today or Yesterday and then post the graphs here.

You can read more about how this in the [CCCM feature](https://github.com/Louisvdw/dbus-serialbattery/wiki/Features#charge-current-control-management)

**Comment by Micha854** [comment]
Hello! I can not see any setting errors. Here are the screens from the BMS

here the BMS limits
<img src="https://bilderupload.org/image/1ec388580-bms-limit.png"/>

battery cells
<img src="https://bilderupload.org/image/44fe88629-bms-cell.png"/>

another question:

my end-of-charge voltage is 27.20. the charging limit goes down to 5A. if larger consumers are running then the battery is charged, although there would be enough pv.... is there a solution for this?

**Comment by Louisvdw** [comment]
I can see that CCCM is working and dynamicly changing your charge current as your battery get full. That all looks fine.
When your battery is not full you get the full 50A and as you reach 100% SOC your charge is reduced to 5A to allow more time for your balancers to work.
When you don't have the battery connected your MPPT does not know at what state your battery is, and it will try and charge with everything it can. This is what DVCC changes. It tells the system that the battery will be in control and it will request a reduced charge when full.
