### ISSUE TITLE
Division by zero if no cells are connected

### ISSUE THREAD

**Issue by Knedox** [Louisvdw/dbus-serialbattery#149]
I am just setting up my battery and dont have any cells connected yet. Seems like this results in a division by zero

INFO:SerialBattery:Starting dbus-serialbattery
INFO:SerialBattery:dbus-serialbattery v0.12
INFO:SerialBattery:Testing LltJbd
ERROR:SerialBattery:>>> ERROR: No reply - returning
INFO:SerialBattery:Testing Ant
ERROR:SerialBattery:>>> ERROR: No reply - returning
ERROR:SerialBattery:>>> ERROR: Incorrect Data
INFO:SerialBattery:Testing Daly
ERROR:SerialBattery:>>> ERROR: No reply - returning
INFO:SerialBattery:Testing Daly
ERROR:SerialBattery:>>> ERROR: No reply - returning
INFO:SerialBattery:Testing Jkbms
INFO:SerialBattery:Connection established to Jkbms
INFO:SerialBattery:DeviceInstance = 1
INFO:SerialBattery:com.victronenergy.battery.ttyUSB0
INFO:SerialBattery:Battery connected to dbus from /dev/ttyUSB0
Traceback (most recent call last):
  File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 176, in publish_battery
    self.publish_dbus()
  File "/opt/victronenergy/dbus-serialbattery/dbushelper.py", line 196, in publish_dbus
    midpoint, deviation = self.battery.get_midvoltage()
  File "/opt/victronenergy/dbus-serialbattery/battery.py", line 247, in get_midvoltage
    return midpoint, abs(1 - half1voltage/half2voltage)*100
ZeroDivisionError: float division by zero

https://github.com/Louisvdw/dbus-serialbattery/blob/d5fe4958f84eb9277b4ac4e6f5f72f07b8624310/etc/dbus-serialbattery/battery.py#L247

**Comment by dropax** [comment]
The log shows communication between driver and BMS. Should be sufficient at this stage.
Beyond that I think it would be rather pointless to catch an error from a BMS that has actually no battery to manage.
