### ISSUE TITLE
Update release to install the cell voltage page

### ISSUE THREAD

**Issue by Knedox** [Louisvdw/dbus-serialbattery#158]
Hello,

i am just trying to install latest release with new cell voltage menu. Unfortunately it seems like the latest release does not include it, even if it states so. 
So i have copied everything myself to /opt.... Now GUI does not start anymore 

file:///opt/victronenergy/gui/qml/main.qml:12:15: Type PageMain unavailable
        initialPage: PageMain {}
                     ^
file:///opt/victronenergy/gui/qml/PageMain.qml:73:3: Type PageBattery unavailable
                PageBattery {}
                ^
file:///opt/victronenergy/gui/qml/PageBattery.qml:186:4: Cannot assign to non-existent property "title"
                        title: qsTr("Details")
                        ^

Now i try to go back to old PageBattery.qml but its not in any .zip or in the repo at all? Where to find it?

Also i am wondering why this LOC here is disabled, is there any reason?

https://github.com/Louisvdw/dbus-serialbattery/blob/master/etc/dbus-serialbattery/jkbms.py#L100

Thanks

**Comment by Louisvdw** [comment]
Fixed in the new beta release
https://github.com/Louisvdw/dbus-serialbattery/releases/tag/v0.12b1
