### ISSUE TITLE
Max Battery Current of 50A is dislayed as 25A CCL value

### ISSUE THREAD

**Issue by geromd** [Louisvdw/dbus-serialbattery#161]
**Describe the bug**
The Victron remote shell show a fixed max charge current (CCL) of 25A:
![Konsole](https://user-images.githubusercontent.com/109993803/181631906-68f3f0be-b29b-4355-89d4-8dc2215425ea.jpg)

The fixed value of 50A in the script is not considered and chages are not shown in the remote shell:
![Script](https://user-images.githubusercontent.com/109993803/181632241-7a9094cc-13c6-4dac-b3d7-08854bff665c.jpg)

**To Reproduce**
1. Open Victron remote Shell
2. Go to folder Serial Batterie
3. Go to folder Parameters
4. Compare CCL value with entry MAX_BATTERY_CURRENT = 50.0 in utils.py

**Expected behavior**
Value of CCL and MAX_BATTERY_CURRENT = 50.0 should be the same

**VenusOS (please complete the following information):**
 - Device type: Multiplus II GX (2629)
 - Firmware Version 481

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: Daly BMS
 - Cells: 16S
 - Interface: USB-RS485

**Comment by geromd** [comment]
After writing my report th value in the remote shell was actualized by themselfe to 50A. However, there was never and entered value of 25A before for the MAX_BATTERY_CURRENT in the utils.py

**Comment by Louisvdw** [comment]
https://github.com/Louisvdw/dbus-serialbattery/wiki/Features#charge-current-control-management
