### ISSUE TITLE
SoC is falling

### ISSUE THREAD

**Issue by dan11hh** [Louisvdw/dbus-serialbattery#171]
**Describe the bug**
I don‘t know if it is a bug, but at two installed systems the SoC shown by serialbattery falls. 
mit works around three weeks perfekt. Voltage was around 3,45V the SoC was 99%. 
now it just shows 90%, at the other (same) system it is at 60%. 

**VenusOS (please complete the following information):**
 - Device type:  Venus OS Raspberry PI at MP 2 5000
 - Firmware Version [e.g. 2.87]

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: JK BMS with EVE 280k
 - Cells: 16
 - Interface: USB-RS485
 
 
It is the JKBMS not your Driver, Louis, but how can I handle that?

**Comment by Louisvdw** [comment]
This would not be a bug in the driver, but rather that the driver is now showing you what is happening inside your battery. 
The SOC value is what your BMS is publishing. The driver is just publishing that the the Victron system.

This can be influence by the formulas and logic that your BMS use.  It could be that there are some cells not up to voltage that is keeping the SOC value lower. Dig a bit into the min/max cell values and check if you see anything strange. The graphs in the advance section in VRM give a lot of great insight into your battery.

**Comment by dan11hh** [comment]
That is my "problem". The Battery Voltages are nearly matching the whole time. The greatest difference which the VRM showed to me is 0,04V while Loading with 65A.

**Comment by Louisvdw** [comment]
Are you using large currents or are your system only using small amounts at a time. 
These BMS use a shunt to measure the current flow and while this is one of the best methods to use it can sometimes struggle to measure small amounts of current. So if you have a 100A BMS but are most of the time using say 1A then it could be that your BMS is not reading that correctly. A shunt has to be calibrated for either large currents or small. Or you need 2 to be able to read small and large currents, which increase the cost so no body builds BMS like that. 

When you are seeing the 0.04V cell difference, is that when your battery is at the highest SOC? What are your voltages at that time? Can you post these 3 graphs from your system for the last full day that shows the problem
![image](https://user-images.githubusercontent.com/26077665/182582312-b22f5a88-4547-483d-96cc-b5027e9343b7.png)

**Comment by dan11hh** [comment]
You're the man! Thanks for your massiv help. The battery is now up for 40 days. I was last week in holiday so the battery wasn't used that much, if that matters...
I just to make sure that i can add  second 16s pack parallel to the existing one. (same config)
![Bildschirmfoto 2022-08-03 um 16 08 36](https://user-images.githubusercontent.com/35640132/182629642-5cfbd4d7-b856-4b0e-9e5c-9f1b264c60b1.png)
![Bildschirmfoto 2022-08-03 um 16 09 23](https://user-images.githubusercontent.com/35640132/182629660-0011e3f1-f5d3-443f-bc93-d781bdf0fd63.png)
![Bildschirmfoto 2022-08-03 um 16 09 43](https://user-images.githubusercontent.com/35640132/182629674-86c53ec1-da25-4fe9-8a3d-d364cc5e820c.png)
![Bildschirmfoto 2022-08-03 um 16 11 46](https://user-images.githubusercontent.com/35640132/182629942-f0866232-ab0d-4e61-a5bb-d15c06fb4c87.png)

Today (first day back) i got a max difference from 0,08V, but just while i load with 65A and just a short time. If i disable loading in the bms the cells will be all back nearby.

**Comment by Louisvdw** [comment]
Your system is looking good. All the values is as I would expect them

**Comment by dan11hh** [comment]
Hmmm thanks again for you answer. i have no idea how to recalibrate the SoC. Did you have any further tipps/ideas?

**Comment by Louisvdw** [comment]
What settings do you have for your JKBMS?

**Comment by dropax** [comment]
To recalibrate SoC in the JKBMS the following procedure works for me:

- discharge to something below 70% (not shure if there is a distict threshold)
- alter the Ah setting, at this point the BMS guestimates a new SoC (you loose cycle count and cycle Ah, take notes if you want to track these values) 
- it looks like you're "missing" 9%, therefore the new SoC should be at least these 9% above the old value 
- recharge to full, SoC will rise and stay at 99% until "true" full charge is reached

You'll see 100% only for the brief moment when the BMS' Max Cell Voltage is hit and the charge-FET gets disabled.
