### ISSUE TITLE
CVL & CCL & DCL Fixed not matching BMS settings

### ISSUE THREAD

**Issue by NunoRgP** [Louisvdw/dbus-serialbattery#187]
**Describe the bug**
SerialBattery/Parameters seem to be oscillating between certain values :

CVL :  55.2 V
CCL : 50 A
DCL : 15A / 30 A

On the JBD BMS settings I am using 50A as maximum charge current and 100 A as discharge current as well as on the utils.py

I selected the SMART Shunt to be used as the battery monitor but it seems the cerboGX is taking the above values on serial battery as the system limits . At the  DCL parameter ( 30A or 15A ) the Inverter throttles down . 

I wand to use the dbus-serialbattery as only a monitoring tool as I currently have 2 batteries in parallel . So I would prefer to use the tool with DVCC off but as soon as I turn it off the inverter gives me the low voltage error and turns on passthrough . 

Is there a way to make these values fixed ? Is this expected behaviour ? 

**Expected behavior**
Have the SerialBattery/Parameters CVL & CCL & DCL as fixed values 

**Screenshots**
![DVCC](https://user-images.githubusercontent.com/3765598/185807689-0239104d-a44b-4f72-ad92-dc103203c903.jpg)
![battery monitor](https://user-images.githubusercontent.com/3765598/185807686-12195596-fd53-4c34-a529-62d1b5478ca1.jpg)
![utils py](https://user-images.githubusercontent.com/3765598/185807703-38c08d6d-589c-4a95-9bcd-f96b063a5bf7.jpg)
![Parameters](https://user-images.githubusercontent.com/3765598/185807767-3fb1d971-85f7-45ae-9439-ab9263567c10.jpg)
![WhatsApp Image 2022-08-21 at 9 32 29 PM](https://user-images.githubusercontent.com/3765598/185807833-8415e3fb-b649-49b2-beee-95a08c48f0c0.jpeg)

**VenusOS (please complete the following information):**
 - Device type:  Cerbo GX
 - Firmware Version 2.85

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: JBD

 - Cells: 16
 - Interface: USB-RS485

**Additional context**

**Comment by NunoRgP** [comment]
Ok I managed to change the settings and it seems they are fixed now, I had to do the CCM_Enable = False . 
After placing it as False the cerboGX is now using the max battery charge current and discharge current from the utils.py  . 

I am only missing now where is the CVL of 55.2 coming from ?

**Comment by Louisvdw** [comment]
Correct. CCCM dynamicly changes your charge current from the SOC value. It does use the battery SOC value not the GX SOC as it is a battery feature.

For the CVL it gets calculated from your cell count. See CVL in [features](https://github.com/Louisvdw/dbus-serialbattery/wiki/Features#features)
