### ISSUE TITLE
Cannot disable driver on Venus GX

### ISSUE THREAD

**Issue by TassieFlash** [Louisvdw/dbus-serialbattery#188]
Installed your driver on a new Venus GX  (Firmware version 2.89)

Decided that I did not like the integration into my existing Victron system.

Running the command...   sh /data/etc/dbus-serialbattery/disabledriver.sh ,to disable the driver fails to work.

I am getting error codes on the Victron mppt 150/60 controller and on the inverter, and cannot resume normal use.

![Screenshot from 2022-08-23 12-17-26](https://user-images.githubusercontent.com/111851138/186098432-43a59c5b-3a4a-4de6-a5fe-e5c027bbf016.png)

**Comment by Louisvdw** [comment]
Once you installed a BMS/Battery your MPPTs are set by the GX system to be connected to the BMS. When the connection to the battery is lost your MPPT will go into this safety mode and you need to tell your MPPT it is safe to work without the BMS.

See https://www.victronenergy.com/live/mppt-error-codes#err_67_-_bms_connection_lost on how to configure the MPPT back to stand alone mode.

**Comment by TassieFlash** [comment]
Hi Louis, I guess there is a similar procedure to rid the Victron RS 48/6000 inverter of its error codes too.

I'll trawl the Victron site for that one. 

Thanks.
