### ISSUE TITLE
Charge Current Limit(CCL) and Discharge Current Limit(DCL) get true/false separate 

### ISSUE THREAD

**Issue by testpaul999** [Louisvdw/dbus-serialbattery#211]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when
- now at Fall I‘d like to bring all power to the Akku and so it I disable CCCM again all.
- But in this case also the discharge will run at 100%  

**Describe the solution you'd like**
- so can you pls separate CCL and DCL that I can only turn off CCL.

**Describe alternatives you've considered**
- nothing 

**Additional context**
- regards :-)

**Comment by Louisvdw** [comment]
fix in #238 
There is now
> CCCM_ENABLE = True
DCCM_ENABLE = True
