### ISSUE TITLE
Editing utils.py does not change CCL accordingly.

### ISSUE THREAD

**Issue by MikeEcho0815** [Louisvdw/dbus-serialbattery#247]
**Describe the bug**
Editing the utils.py (MAX_BATTERY_CURRENT) leads to wrong Parameter in Cerbo GX CCL

**To Reproduce**
1. Editing the utils.py (MAX_BATTERY_CURRENT)
2. Check Cerbo GX Parameters > CCL

**Expected behavior**
I would expect the same value as edited in the utils.py

**Screenshots**
![image](https://user-images.githubusercontent.com/45940028/194885766-37ae41fe-1e09-47aa-a647-951bcc78e0c7.png)
![image](https://user-images.githubusercontent.com/45940028/194885810-10c61c82-a0eb-4447-8d3b-a480316180c8.png)

**VenusOS (please complete the following information):**
 - Device type: Cerbo GX
 - Firmware Version : v2.91

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: JKBMX 150A
 - Cells: 16
 - Interface: USB-RS485

**Comment by Louisvdw** [comment]
See https://github.com/Louisvdw/dbus-serialbattery/wiki/Features#charge-current-control-management
Your SOC % are between 95% - 98% => 1/4 Max charge   (105A/4 = 26,25A)

**Comment by MikeEcho0815** [comment]
Thank you for pointing me in the direction!
