### ISSUE TITLE
"Master BMS" aggregating all infos from connected BMSes

### ISSUE THREAD

**Issue by chiefjoejj** [Louisvdw/dbus-serialbattery#266]
When connecting more than one BMS (battery pack) to the Venus-OS-device it would be great if dbus-serialbattery could "aggregate" all relevant data (i.e. SoC, wattage, MinCellV, MaxCellV, temp, battery modules, etc.) in one "device" that then can be selected as "Battery monitor" in Venus OS. Main reason would be to dynamically limit the dis-/charging current depending on the number of connected battery packs - and the "median" SoC of course.

Would that be possible? I am planning 6 parallel battery packs with a jbd-bms for each battery pack and therefore this feature would be awesome... BTW: Some readers of my blog (meintechlog.de) who are planning to upgrading their battery capacity already "requested" that feature as well.

Best regards
Jörg

**Comment by Louisvdw** [comment]
Hi
Yes this is what #8 will do. You can subscribe to that ticket for notifications
