### ISSUE TITLE
VenusOS 2.91 -  dbus-serialbattery v0.13 - JK-BMS RS485 not seen in Venus OS

### ISSUE THREAD

**Issue by ducloslaurent** [Louisvdw/dbus-serialbattery#273]
Hello Louis,

_**Bug :**_ 
impossible to see the JK BMS model JK-B2A24S20P in the Venus OS

_**Installation :**_ 
Venus OS : v2.91 mounted on a Rpi3B+
Additional content : Package Manager (ShutDownMonitor + RpiDisplaySetup + GuiMod installed)
Victron hardware : Multiplus 2 48/3000 (not a GX version)
-> DVCC activated
BMS : JK-B2A24S20P - SW version : V10.07 - Version V4.8.0
JK-BMS RS485 module plugged into the GPS port of the GPS + using a DSD TECH SH-U10L Câble USB vers RS485 (https://www.amazon.fr/gp/product/B08DXLJF8J/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

_**Dbus-Serialbattery installation :**_ 
made with SSH access using Putty (root access) : 
-> wget https://raw.githubusercontent.com/Louisvdw/dbus-serialbattery/master/etc/dbus-serialbattery/installrelease.sh
   NO ISSUE
-> sh installrelease.sh
   2 message reporting "cp: omitting directory '/data/etc/dbus-serialbattery/qml'" and "cp: omitting directory '/data/etc/dbus-serialbattery/service'"
-> reboot
   NO ISSUE

_**Defect retest :**_ 
Rpi Reboot have been done 2 times
RS485/USB converter have been tested on all Rpi USB port and also on an USB extender port

Test made with VenusOS 2.92 -> same result, impossible to see the JK-BMS on the Rpi screen

Installation have already work (JK-BMS shown on the Rpi but I don't remember the Venus OS version using the same JK-BMS RS485 module and RS485/USB converter)

_**Printscreen :**_ 

Dbus-serialbattery installation
![Dbus-Serialbattery installation](https://user-images.githubusercontent.com/40505802/197886730-ef3c2dca-7be6-4889-b428-2bc9a26650d8.JPG)

DVCC activation
![DVCC activation](https://user-images.githubusercontent.com/40505802/197888524-3c1a1c82-d101-4883-8786-c90ce98786cd.JPG)

VICTRON setup
![Victron setup](https://user-images.githubusercontent.com/40505802/197887051-2e4e70af-98ff-4dc4-83bb-51abdc231e8f.JPG)

Thanks for your support on this issue and great work for the JK-BMS adaptation on Venus OS

**Comment by Louisvdw** [comment]
Can you post the log files here please
https://github.com/Louisvdw/dbus-serialbattery/wiki/Troubleshoot

**Comment by ducloslaurent** [comment]
Hello Louis,

1st log file -> 1st message error
Super user is activated (see 2nd screen shot)
I'm connected through Putty as root and the root entry seams to be OK

![Log file 1](https://user-images.githubusercontent.com/40505802/198138507-e4743032-cc58-4ba8-9f9e-288b91f3adef.JPG)

![Super User activation](https://user-images.githubusercontent.com/40505802/198138681-9f3993e6-46eb-40d5-b87d-cf43023b6b99.JPG)

**Comment by Marvo2011** [comment]
@ducloslaurent You have to use `cat`

```cat /data/log/serial-starter/current```

And please hide your IPs for safety reasons...

**Comment by Louisvdw** [comment]
@ducloslaurent the problem is you cannot run the file, you need to view it's contents. So either by using cat like @Marvo2011 mentioned, or if you look at the bottom of the troubleshoot you will see the examples for tail 
> tail -f /data/log/serial-starter/current
tail -f /data/log/dbus-serialbattery.ttyUSB0/current

The IP range 10.*.*.* is an private IP range and so no traffic on that will be routed to the internet. So it is save to show
https://en.wikipedia.org/wiki/Private_network

**Comment by Marvo2011** [comment]
@Louisvdw I' know 10... is private, I mean the 84... with tunnel port. https://www.victronenergy.com/media/pg/Cerbo_GX/en/faq.html#UUID-9977528a-a1d7-c785-64af-2ab39d915b25
Seams a Victron server IP should be save...

**Comment by Louisvdw** [comment]
Ah! I missed that in the picture. You are correct

**Comment by karrycrasto2008** [comment]
I had to use combination of following 2 adapters to make it work with JK BMS and Venus OS
USB to RS485([https://robu.in/product/usb-rs485-ttl-serial-converter-adapter-ft232/)=>](https://robu.in/product/usb-rs485-ttl-serial-converter-adapter-ft232/) RS485 to TTL(https://robu.in/product/ttl-to-rs485-power-supply-converter-board-3-3v-5v-hardware-auto-control-module/)


![image](https://user-images.githubusercontent.com/3477857/198993308-17b1dea2-0cbc-4121-855d-085a87b1c548.png)

**Comment by ducloslaurent** [comment]
@karrycrasto2008 thanks for your answer, but I can not see how both adapter are plugged to the JK-BMS as only 1 RS485 output on the JK-BMS.
No more use of the JK-BMS RS485 adapter?

![JK-BMS wiring](https://user-images.githubusercontent.com/40505802/200042154-a6e491eb-03fd-429c-9514-666e82f502be.jpg)

**Comment by WaldemarFech** [comment]
If you have the JK-BMS RS485-Adapter, then it already converts TTL (The Rx and Tx Pins in the "GPS" Port) to RS485.
Then you only need a RS485 -> USB Adapter. In best case with a FTDI-Chip.

Please print, as @Louisvdw said, the output of the following command:
`tail -f /data/log/serial-starter/current`

It is possible, that you have an other Chip on your converter - then maybe we need to change a victron file, to use modbus on your chip.

But you can also try to change A and B in your Converter - sometimes it's printed wrong on the china converter.

The Jumpers in the last picture (under the title USB to Rpi) should be all set to supply the rs485 driver on that board. But you don't have to connect anything else than A and B (even not GND)

**Comment by karrycrasto2008** [comment]
JK-BMS RS485 adapter was not available for me without a very long wait for it to be imported from China so i had to use the adapter i have mentioned above to convert TTL (The Rx and Tx Pins in the "GPS" Port) to RS485. It has been working fine since last 2 months now. Note that the adapter has max input voltage of 33 volts so you may need a voltage converter to reduce it if your battery bank voltage is higher than that.

**Comment by ducloslaurent** [comment]
> If you have the JK-BMS RS485-Adapter, then it already converts TTL (The Rx and Tx Pins in the "GPS" Port) to RS485. Then you only need a RS485 -> USB Adapter. In best case with a FTDI-Chip.
> 
> Please print, as @Louisvdw said, the output of the following command: `tail -f /data/log/serial-starter/current`
> 
> It is possible, that you have an other Chip on your converter - then maybe we need to change a victron file, to use modbus on your chip.
> 
> But you can also try to change A and B in your Converter - sometimes it's printed wrong on the china converter.
> 
> The Jumpers in the last picture (under the title USB to Rpi) should be all set to supply the rs485 driver on that board. But you don't have to connect anything else than A and B (even not GND)

@WaldemarFech , yes I have the JK-BMS adapter
Below the print screen for the commande "tail -f /data/log/serial-starter/current"

![JK-BMS putty command](https://user-images.githubusercontent.com/40505802/202101668-2378f45c-4a86-49d3-8cac-c220fa0f36ad.JPG)

But you can also try to change A and B in your Converter - sometimes it's printed wrong on the china converter.
-> OK I will try it

The Jumpers in the last picture (under the title USB to Rpi) should be all set to supply the rs485 driver on that board. But you don't have to connect anything else than A and B (even not GND)
-> OK

**Comment by Louisvdw** [comment]
The dbus-serialbattery driver is running as per the log file you posted. Now we need to see what happens in the dbus-serialbattery.ttyUSB1/current log file, but my guess would be that it does not get a reply. That would indicate problems with the wiring or connections.

**Comment by ducloslaurent** [comment]
@Louisvdw see below the result for the command tail -f /data/log/dbus-serialbattery.ttyUSB1/current

![Commande rpi](https://user-images.githubusercontent.com/40505802/202846139-ccbfc7b3-5aeb-4d1b-9a24-20e467739873.jpg)

-> wiring problem?

**Comment by WaldemarFech** [comment]
Maybe yes. There ist absolute no communication from the BMS.

Would it be an option for you to make a video of your wiring and upload a short video on YouTube or so? Then we could see where you have plugged in the cables and which color and so on.

**Comment by Louisvdw** [comment]
@ducloslaurent if you are still using the adapter that you listed in the opening post I think that might be the issue. I'm not sure the SILICON LABS CP2102 chip is part of the drivers in the VenusOS. There is no reply from a BMS.

Try using something like 
https://www.amazon.fr/RS485-C%C3%A2ble-adaptateur-convertisseur-RS485-avec-Usb-rs485-we-1800-bt/dp/B0757N8WPG
https://www.amazon.fr/Convertisseur-Industriel-Adaptateur-Anti-Foudre-Protection/dp/B0B87D9LNC

**Comment by ducloslaurent** [comment]
@Louisvdw second link product ordered and received, I will try to make the change and kepp you informed.

**Comment by ducloslaurent** [comment]
Hello @Louisvdw , some progress, wiring made with 2nd proposed converter, yellow wire on A pad / white wire on B pad and TXD led is flashing (Power led red continuously)
See below both print screen for command : 

tail -f /data/log/serial-starter/current

![Capture d’écran (4)](https://user-images.githubusercontent.com/40505802/203520623-c23cc187-cabf-49fc-93fd-cbe3185f5919.png)

tail -f /data/log/dbus-serialbattery.ttyUSB1/current

![Capture d’écran (5)](https://user-images.githubusercontent.com/40505802/203520669-ec261135-c95c-4ad8-9922-efc93cb812de.png)

But no BMS signal on the Venus OS

![Capture d’écran (6)](https://user-images.githubusercontent.com/40505802/203520863-de017505-6454-4cc7-ab83-1b8ea10ab5e8.png)

**Comment by Louisvdw** [comment]
@ducloslaurent you will see the serial-starter log that the port is for ttyACM0 which mean you need to get that log file instead of ttyUSB1 for the serialbattery log.

**Comment by ducloslaurent** [comment]
@Louisvdw , yes sorry, not seen that the test have not been done on the good USB
Below th test on the ttyUSB1

![Capture d’écran (8)](https://user-images.githubusercontent.com/40505802/203714606-4129a476-c8a6-4a05-b4ca-ec45dd418fd5.png)

**Comment by Louisvdw** [comment]
The driver is still not receiving a reply. Can you send us detail pictures of your where your adapter plugs into your GX device, each piece until plugged into the BMS on the GPS port. I need to see each connection please.

**Comment by ducloslaurent** [comment]
@Louisvdw 
See below complete wiring from BMS to RPi 3B+ used for Venus OS emulation :

BMS plugged (JK-BMS version JK-B2A24S20P RS485 - According to JK-BMS, the RS485 is on the GPS port)
![1669278809013](https://user-images.githubusercontent.com/40505802/203734821-980f591e-cd72-4ebb-adc9-1f5c36fc0fac.jpg)

![Capture d’écran (9)](https://user-images.githubusercontent.com/40505802/203735259-7c9efb0d-35c5-445b-bb6f-fc0ec2658762.png)

JK-BMS RS-485 adaptor 
![1669278808988](https://user-images.githubusercontent.com/40505802/203734863-46adc671-25c2-4177-a732-075a67c73b8e.jpg)

Connection between JK-BMS RS-485 adaptor and RS485 convertor (only yellow and white wire plugged, not the black wire on GND)
![1669278808966](https://user-images.githubusercontent.com/40505802/203734891-5eb56f8b-3204-4c8e-bc08-0a388e0d516f.jpg)

Connection from RS485 convertor to RPi 3B+
![1669278808942](https://user-images.githubusercontent.com/40505802/203734902-59ac3b3a-10a5-4d09-9e2f-f6df4a52c775.jpg)

**Comment by WaldemarFech** [comment]
> TXD led is flashing

there must be something wrong with the wiring or the jk converter / connector.

If your tx pin or your adapter is blinking, then the serial battery driver is sending messages and is waiting for answers.
But if A and B is over cross, then it don't work.
If the jk rs485/TTL converter is broken or has no good connection in the GPS port, then it don't works, too.

If you have a second USB/rs485 converter, then you can plug it in your computer and run a program like hterm.
choose the com-port, choose 115200 baud, click connect, make a selection in HEX and let it make a new line after 200ms or so. after some receptions you can disconnect. there should be a message in hex (i have to look in the code to tell the exactly message) which asks the different BMSs if they are there.

Then you would know, that both of your usb rs485 converters are working fine and the problem is somewhere in the jk converter or the wiring to the GPS port.

try to crossover A and B and replug the converters.

**Comment by ducloslaurent** [comment]
Changing the JK-BMS RS485 adaptor and crossover A & B -> it is alive and visible on the Venus OS

Many, many thanks to @Louisvdw and @WaldemarFech 

![Capture d’écran (10)](https://user-images.githubusercontent.com/40505802/203743068-ea278aff-e068-451c-b49c-ff799a98ef52.png)
