### ISSUE TITLE
JK BMS looses connection after battery high voltage alarm. 

### ISSUE THREAD

**Issue by karrycrasto2008** [Louisvdw/dbus-serialbattery#279]
JK BMS looses connection after battery high voltage alarm. 

![image](https://user-images.githubusercontent.com/3477857/198991363-73702aa1-a745-4e8f-9f31-856636212acb.png)

**VenusOS
 - Device type:  Raspberry Pi
 - Firmware Version 292

**Battery/BMS
 - BMS/Battery type: JK
 - Cells: 8 , 150 AH
 - Interface: USB to RS485(https://robu.in/product/usb-rs485-ttl-serial-converter-adapter-ft232/)=> RS485 to TTL(https://robu.in/product/ttl-to-rs485-power-supply-converter-board-3-3v-5v-hardware-auto-control-module/)
 - Active balance is on. 
This has been happening from beginning from setup, I think it happens when the cells reach max voltage and the BMS stops charging the battery.
It resolves once Venus OS is rebooted.

**Comment by Louisvdw** [comment]
The JKBMS reboots when it gets a high voltage alarm and then the connection is lost. I have seen that happen. 
Check what the min/max cell voltages are when that happens. (VRM Advance section graphs) 
Most likely some of your cells are imbalanced which raise the alarm.

**Comment by karrycrasto2008** [comment]
This is what it looks like in VRM for min/max cells
![image](https://user-images.githubusercontent.com/3477857/198997582-1447466c-7201-49df-aff3-df07544e2bff.png)

**Comment by Louisvdw** [comment]
Do you see anything in the log files? https://github.com/Louisvdw/dbus-serialbattery/wiki/Troubleshoot
