### ISSUE TITLE
JKBMS Venus OS integration

### ISSUE THREAD

**Issue by Marcodit** [Louisvdw/dbus-serialbattery#29]
Add JKBMS Venus OS integration to the driver:

- [x] SOC
- [x] Battery voltage
- [x] Charge/discharge current
- [x] Temprature
- [x] Min/max cell voltages
- [ ] protection notifications
[BMS 485 instruction.pdf](https://github.com/Louisvdw/dbus-serialbattery/files/6916652/BMS.485.instruction.pdf)
[BMS CAN instruction.pdf](https://github.com/Louisvdw/dbus-serialbattery/files/6916654/BMS.CAN.instruction.pdf)
[BMS-CAN2-english.pdf](https://github.com/Louisvdw/dbus-serialbattery/files/6916655/BMS-CAN2-english.pdf)

**Comment by Marcodit** [comment]
> 
[BMS-CAN2-english (1).pdf](https://github.com/Louisvdw/dbus-serialbattery/files/6913139/BMS-CAN2-english.1.pdf)

**Comment by Marcodit** [comment]
[BMS-CAN2-english (1).pdf](https://github.com/Louisvdw/dbus-serialbattery/files/6913141/BMS-CAN2-english.1.pdf)
[BMS CAN instruction(2).pdf](https://github.com/Louisvdw/dbus-serialbattery/files/6913143/BMS.CAN.instruction.2.pdf)
[BMS 485 instruction(1).pdf](https://github.com/Louisvdw/dbus-serialbattery/files/6913144/BMS.485.instruction.1.pdf)

**Comment by juanmijm** [comment]
Ohhh, I think there are a lot of people interested in this, hopefully it can be done. THANK YOU!

**Comment by domoticadcm** [comment]
wow!! it´s just what I need!!! thanks in advance

**Comment by baizan1** [comment]
Yes, i need this integration too, my JK don't comunicate with Victron. Thanks.

**Comment by gcruzsan** [comment]
A great BMS, and with this project would be even bigger.

**Comment by Louisvdw** [comment]
Is anyone willing to sponser a BMS that we can use for development?

**Comment by Marcodit** [comment]
> Is anyone willing to sponser a BMS that we can use for development?

How it can be done?

**Comment by Louisvdw** [comment]
> > Is anyone willing to sponser a BMS that we can use for development?
> 
> How it can be done?

If you have a BMS that you do not use, you can send that to me.
Or I can look at price to order one and we can get sponsers through the Ko-fi sponser link. Just mention JKBMS in Ko-Fi and I will know.

**Comment by Marcodit** [comment]
> > > Is anyone willing to sponser a BMS that we can use for development?
> > 
> > 
> > How it can be done?
> 
> If you have a BMS that you do not use, you can send that to me.
> Or I can look at price to order one and we can get sponsers through the Ko-fi sponser link. Just mention JKBMS in Ko-Fi and I will know.

Ok, thank you,  I will try to get sponsors, can you have a look at the BMS, and if you need just one with the less AMP is less expensive.. because for the same model, there are various AMP's.

**Comment by diybateriaslifepo4** [comment]
> 
> 
> Is anyone willing to sponser a BMS that we can use for development?

Hello, I need to talk with you about this, how can we talk in private?
send me a email for example: DIY.LIFEPO4.europeangroup@gmail.com

**Comment by domoticadcm** [comment]
https://www.aliexpress.com/item/4001192978656.html
there you can get BMS, rs485, and/or CAN modules for the easiest connection

**Comment by Louisvdw** [comment]
> > Is anyone willing to sponser a BMS that we can use for development?
> 
> Hello, I need to talk with you about this, how can we talk in private?
> send me a email for example: [DIY.LIFEPO4.europeangroup@gmail.com](mailto:DIY.LIFEPO4.europeangroup@gmail.com)

You can send PM to me on the forum
https://energytalk.co.za/u/louisvdw

**Comment by juanmijm** [comment]
> > > Is anyone willing to sponser a BMS that we can use for development?
> > 
> > 
> > Hello, I need to talk with you about this, how can we talk in private?
> > send me a email for example: [DIY.LIFEPO4.europeangroup@gmail.com](mailto:DIY.LIFEPO4.europeangroup@gmail.com)
> 
> You can send PM to me on the forum
> https://energytalk.co.za/u/louisvdw

ok, you have MP ;)

**Comment by Aea263** [comment]
Having support for jkbms would be awesome!!!!!

**Comment by sgregori** [comment]
Wow, that's really interesting to use it in my JK BMS. Thanks!

**Comment by RTW22** [comment]
I think what you do is incredible

**Comment by sapcmc** [comment]
Made a contribution via kofi. Let's get this done

**Comment by JoanQA** [comment]
That's really interesting.

**Comment by Louisvdw** [comment]
I've created the first beta build for the JKBMS. 
If anyone wants to try it out and let me know if you find any problems.
Large features still outstanding is any cell data (min/max cells and voltages) and alarms.

https://github.com/Louisvdw/dbus-serialbattery/releases/tag/v0.7beta1
https://github.com/Louisvdw/dbus-serialbattery/wiki/How-to-install

**Comment by Louisvdw** [comment]
v0.7 beta2 adds support for cell values and a few fixes.
https://github.com/Louisvdw/dbus-serialbattery/releases/tag/v0.7beta2

**Comment by Louisvdw** [comment]
JKBMS is now supported in the latest release build
