### ISSUE TITLE
omitting directory on 2.92 EasySolar-II GX

### ISSUE THREAD

**Issue by Fabbec1** [Louisvdw/dbus-serialbattery#290]
**VenusOS (please complete the following information):**
 - Device type: [e.g. VenusGX EasySolar-II GX]
 - Firmware Version [e.g. 292]

after install 
root@EasySolar-IIXXXXXXXXXXXXX:~# sh installrelease.sh
cp: omitting directory '/data/etc/dbus-serialbattery/qml'
cp: omitting directory '/data/etc/dbus-serialbattery/service'

**Comment by Louisvdw** [comment]
Thanks for your notification.
Those are just warnings that can be ignored. The scripts seperately copy those folders to where they need to be, so the driver will work fine. 
This warning has also been suppressed in the new beta release and will ship in the next version 👍
