### ISSUE TITLE
Daly BMS integration

### ISSUE THREAD

**Issue by Louisvdw** [Louisvdw/dbus-serialbattery#3]
Add the Daly BMS basic communication to the driver.

- [x] SOC
- [x] Battery voltage
- [x] Charge/discharge current
- [x] Temprature
- [x] Min/max cell voltages
- [ ] protection notifications

[Part 4_ Daly RS485+UART Protocol.pdf](https://github.com/Louisvdw/dbus-serialbattery/files/5926615/Part.4_.Daly.RS485%2BUART.Protocol.pdf)

**Comment by neoneddy** [comment]
Up Vote

**Comment by gyrex** [comment]
Great work on this project mate! I'd love to see this added please

**Comment by svaeyens** [comment]
Up Vote

**Comment by pau1phi11ips** [comment]
This would be awesome!

**Comment by pau1phi11ips** [comment]
This would be awesome!

**Comment by MichaelStadler91** [comment]
Would be very nice! How is the current status?

**Comment by Louisvdw** [comment]
> Would be very nice! How is the current status?

I already have code that can read the SOC for the Daly. Now I need to move the code a bit so that it can easily be shared between the current battery driver and the Daly code (issue #11) and then I can give you Daly users something to test.

**Comment by pau1phi11ips** [comment]
Do you have a rough estimate to when the Daly code will be available @Louisvdw?

**Comment by Louisvdw** [comment]
I hope to have a first version for the the Daly's SOC at the end of May.

**Comment by neoneddy** [comment]
Awesome, do you have a paypal or something to donate to?

**Comment by dreadnought** [comment]
@Louisvdw you can have a look at it if you like: https://github.com/dreadnought/python-daly-bms

**Comment by Louisvdw** [comment]
> Awesome, do you have a paypal or something to donate to?

Yes you can use Kofi. https://ko-fi.com/louisvdw

**Comment by yannickudb** [comment]
Up vote!

**Comment by Conspir3D** [comment]
+1

**Comment by Louisvdw** [comment]
There is a new [beta build v0.5beta2](https://github.com/Louisvdw/dbus-serialbattery/releases/tag/v0.5beta2) for the initial Daly BMS integration for those that want to test it and give feedback.
This build should work for both the RS485 and UART connection, update the battery SOC, voltage and current in the GX device.

Download the venus-data.tar.gz from beta2 and FTP it to your GX/pi. 
Extract using `tar -zxf venus-data.tar.gz -C /data`
Reboot and let me know if it works. 
Those mini 4sell Daly BMS seem to be running a different protocol, so I don't expect them to work.

**Comment by pau1phi11ips** [comment]
Awesome, I'll give it a go tonight. Excited! 😀

**Comment by pau1phi11ips** [comment]
@Louisvdw I've installed Beta 2 on my Cerbo GX. It's reading the values but only for a split second.

I made a screen recording: https://photos.app.goo.gl/n8SuuhjrU6c5bxQAA

**Comment by Louisvdw** [comment]
@pau1phi11ips do you have SSH access to the GX to copy the log file and attach it here? /data/log/dbus-serialbattery.ttyUSB0/current

**Comment by pau1phi11ips** [comment]
Attached

**Comment by pau1phi11ips** [comment]
Struggling to attach the log directly but could get a screenshot.
![Screenshot_20210622-071301](https://user-images.githubusercontent.com/677264/122873333-89907e00-d329-11eb-9cc4-9d89cea11087.png)

I think the error it due to my BMS only having 1 temperature sensor.

**Comment by Louisvdw** [comment]
I think you are corect. That temp sensor seems to be the issue.

**Comment by pau1phi11ips** [comment]
I'll try and get it working here and post the results. I don't really know Python (just PHP and JavaScript) but think I can handle removing the temp2 references to see if that sorts it. At least that will nail there culprit down.

**Comment by Louisvdw** [comment]
@pau1phi11ips can you check if this fix your temp sensor issue
[venus-data.tar.gz](https://github.com/Louisvdw/dbus-serialbattery/files/6691664/venus-data.tar.gz)

**Comment by pau1phi11ips** [comment]
@Louisvdw Yep, working now thanks! 😎

**Comment by pau1phi11ips** [comment]
One word of caution. I have a 24V LiFePO4 battery and usually charge to 3.35V/cell = 26.8V.

The charge limit on the Multiplus II is set to 26.8V. The battery voltage was 26.7V as soon as I enabled DVCC the Mutliplus started putting 50A into the battery. It was at 27.1V in no time with no sign of stopping.

It looks like because the driver isn't getting Vmax from the BMS it might be using the default 55V?

[](url)
![DVCC](https://user-images.githubusercontent.com/677264/123073683-8cb16a00-d40e-11eb-903a-2477dbe49390.JPG)

Enabling the Limited charge voltage in the DVCC settings sorted it out but this isn't the default setting so beware!

**Comment by Louisvdw** [comment]
Thanks for highlighting @pau1phi11ips 
All the current features of the driver will still apply. What you are referring too is described under  point 7, but perhaps I will expand that to mention the voltages. The driver works on an upper limit of 3.45V per cell. 
If you want to lower either the charge current of voltage you can set those under DVCC.

**Comment by pau1phi11ips** [comment]
OK, thanks, I was worried it was using the default voltage the **Maximum Charge voltage** is set to as soon as you enable **Limit managed battery charge voltage**.

**Comment by Louisvdw** [comment]
The battery publish the discharge current, charge current and charge voltage (for the driver that is 60A,50A, 3.45V x cell_count)
You can limit the discharge current under ESS. The lowest value between that limit and the driver will be used.
You can limit the charge current and/or voltage in DVCC. The lowest value between that and the driver will be used.

This is there for you to override (lower) the defaults. It is normally used more when you set up your battery and want to give it time to balance and settle, but it works well for our needs in this case as well.

**Comment by pau1phi11ips** [comment]
Thanks for the info. Much appreciated.

BTW, I've edited my daly.py to change the polarity of the current value so it's the same direction as the value from the Victron BMV 712. It's definitely wired the right way around around ;)

Changed
`self.current = (current- 30000) / 10`
to 
`self.current = -1 * (current- 30000) / 10`

This is how it looks now
![Current direction 2](https://user-images.githubusercontent.com/677264/123079670-10218a00-d414-11eb-9af7-4f3bd9060abc.JPG)
![Current direction](https://user-images.githubusercontent.com/677264/123079684-1283e400-d414-11eb-9c38-6e4c8662cd98.JPG)

**Comment by Louisvdw** [comment]
Inverting should show a negative draw on the battery. I'll recheck the Daly protocol, but just from looking at you screenshot with the Miltiplus II your change does look correct.

**Comment by yannickudb** [comment]
Got my small daly 4S BMS today, didn't get it working. Anyone who want to help?

**Comment by Louisvdw** [comment]
@yannickudb can you upload the log file for us. See the trouble shoot section in the readme on how to do that.

**Comment by yannickudb** [comment]
I Will do tonight. But i've been messing around with the bms, and found the 4s needs another pc program. I suspect i uses other communication. Any way i can help with that?

**Comment by Louisvdw** [comment]
I think you are correct.
We need the communications protocol for that. If you can find the protocol documentation, open a new ticket and attach that doc.

**Comment by Louisvdw** [comment]
Implemented in release V0.5

**Comment by yannickudb** [comment]
> I think you are correct.
> We need the communications protocol for that. If you can find the protocol documentation, open a new ticket and attach that doc.

I did, have attached a PDF!

**Comment by janekx** [comment]
[0612b045a09d492f5593ebf9b24742b3.pdf](https://github.com/Louisvdw/dbus-serialbattery/files/8946050/0612b045a09d492f5593ebf9b24742b3.pdf)
Daly 1.2v protocol
