### ISSUE TITLE
Daly BMS 16 Cellnumber

### ISSUE THREAD

**Issue by Fabbec1** [Louisvdw/dbus-serialbattery#30]
**Describe the bug**

**To Reproduce**
1. Go to Cell Number
4. See error All Cell Numbers are one to hi real Cellnumber is 2 and Venus show Cellnumber 3

**Screenshots**

**VenusOS (please complete the following information):**
 - Device type: Raspberry Pi]
 - Firmware Version 266

**Battery/BMS (please complete the following information):**
 - BMS/Battery Daly 100A
![IMG_4816](https://user-images.githubusercontent.com/63177995/128347771-2246cb76-4452-412a-bec0-0849ec0b26c4.PNG)
![IMG_4825](https://user-images.githubusercontent.com/63177995/128347826-6e30772e-b746-4f13-95f8-87b05949fee7.PNG)

 - Cells: 16
 - Interface: USB-RS232

**Additional context**

**Comment by Louisvdw** [comment]
@Fabbec1 I fixed this. It will be included the next release.
