### ISSUE TITLE
Calculating the SOC value at jkbms

### ISSUE THREAD

**Issue by Bonzai10** [Louisvdw/dbus-serialbattery#304]
Hi,
it is possible to calculate the SOC value, available amps and consumed amps with the driver.

Reason: The values of the JKBMS deviate quite a bit from reality over time due to the "Abnormal release of current sensor" error.

So far I had the problem that the BMS had e.g. 98% SOC, then it was only charged with 5 amps, although the voltage was only 53.6. With the version of WaldemarFech the loading/unloading problem is already fixed. Thanks.

Now it would be nice to see a real SOC value.
It would be nice to calculate like a shunt which synchronizes itself again and again.
Likewise, the integration of the float mode in the WaldemarFech version would be very nice

![grafik](https://user-images.githubusercontent.com/119003116/204149775-f025d7f1-2ba4-4f85-93da-90c1f3ec5878.png)

**Comment by Bonzai10** [comment]
![grafik](https://user-images.githubusercontent.com/119003116/204149718-fbccd6fb-5b5d-4c49-b161-24519792faff.png)

**Comment by Louisvdw** [comment]
Hi
It will not be easy to calculate SOC in the driver.

**Comment by Bonzai10** [comment]
OK. Thank´s for the info

**Comment by Dr-Gigavolt** [comment]
Perhaps this can help you:
https://github.com/Dr-Gigavolt/dbus-aggregate-batteries
