### ISSUE TITLE
Daly Smart BMS - Read alarms

### ISSUE THREAD

**Issue by Fabbec1** [Louisvdw/dbus-serialbattery#31]
1. Allow unloading ON/OFF MosFet as a function from victronOS - as a function Controllable e.B of ModBus address 280.
![Unbenannt](https://user-images.githubusercontent.com/63177995/128350087-54f5b3b3-f20b-4e56-8830-6b9e68c214b8.png)
See https://github.com/Louisvdw/dbus-serialbattery/issues/26

2. Get installed and available capacity from the daly 
![IMG_4817](https://user-images.githubusercontent.com/63177995/128349923-cae26bc7-16e5-4968-a990-7e1b9e3bd9cf.PNG)

3. Read alarms
![IMG_4825](https://user-images.githubusercontent.com/63177995/128349819-adc43a1e-d9bf-4ddc-a85f-b250ab6758ee.PNG)
![IMG_4818](https://user-images.githubusercontent.com/63177995/128349847-10cd4126-6951-461c-9269-6e6df762bcbd.PNG)
See https://github.com/Louisvdw/dbus-serialbattery/pull/90

thx for your Work on this Driver

**Comment by Louisvdw** [comment]
Alarms have been included in PR #90 and should be in the next version released

**Comment by transistorgit** [comment]
Installed capacity is read from the config
remaining capacity is installed capacity * SOC
both is already displayed
![image](https://user-images.githubusercontent.com/6627385/235081977-428c1eca-c1a4-443d-afab-3cefc0f93006.png)

Is this not what is wanted? Should it be read from the bms?

**Comment by mr-manuel** [comment]
It would be nice, if the installed capacity is read from the BMS. Is this data available? This would help to identify multiple BMS by changing slightly the capacity on the BMS.

**Comment by transistorgit** [comment]
as of the protocol snippets @teefix posted, it should be possible to read the rated capacity. But also the BMS board number. Will look into both and also try to set SOC, as it is usefull for me also.

**Comment by mr-manuel** [comment]
That would be great!

**Comment by transistorgit** [comment]
capacity is working.  It is read from bms now.
![image](https://user-images.githubusercontent.com/6627385/235219054-0d25490f-6a80-4ad0-8c1e-ec79976b4a63.png)



board number not. I can read it, but when I use the daly pcmaster software to set a number other than 1 the bms stops working with "aquisition aef error" or so... so I stoped working on it.

**Comment by mr-manuel** [comment]
Unfortunately I have no hint.

**Comment by teefixx** [comment]
I use a flow in Nodered, which switches to float voltage, after the max charge is reached for 15min and stays there until SOC is below 95%. Still the BMS always is only on 99.x%. My plan is to trigger SOC reset to 100% when I change to float voltage...
I'm not an experienced programmer, so don't blame me if this could be done in a shorter way, I anyway attach the flow for your information. The flow is used to control CVL via a PID controller not to overcharge the cells, the "float or not" function controls if CVL is changed to float voltage.

<img width="1899" alt="image" src="https://user-images.githubusercontent.com/35899354/235223263-e89a727d-2b5d-42a3-9aa1-ce5dae06f135.png">
[float.txt](https://github.com/Louisvdw/dbus-serialbattery/files/11356266/float.txt)

**Comment by teefixx** [comment]
> capacity is working. It is read from bms now. ![image](https://user-images.githubusercontent.com/6627385/235219054-0d25490f-6a80-4ad0-8c1e-ec79976b4a63.png)
> 
> board number not. I can read it, but when I use the daly pcmaster software to set a number other than 1 the bms stops working with "aquisition aef error" or so... so I stoped working on it.

It's odd that changing the board number does not work, there is a guy at the diy solar forum who did it successfully :https://diysolarforum.com/threads/interfacing-several-daly-bms-via-rs485.17998/#post-215831

After that he was able to send gather serial data from the different boards by exchanging X40 to X41 for board No2: https://diysolarforum.com/threads/decoding-the-daly-smartbms-protocol.21898/page-2#post-385365

**Comment by mr-manuel** [comment]
1. Is handled with https://github.com/Louisvdw/dbus-serialbattery/issues/26
2. Is done.
3. Is done.
