### ISSUE TITLE
Midpoint deviation 

### ISSUE THREAD

**Issue by merlep** [Louisvdw/dbus-serialbattery#311]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VenusOS (please complete the following information):**
 - Device type: [e.g. VenusGX, Cerbo, Raspberry Pi]
 - Firmware Version [e.g. 262]

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: [e.g. LTT, Daly]
 - Cells: [e.g. 16]
 - Interface: [e.g. USB-RS485, USB-RS232, Ve.Direct]

**Additional context**

**Comment by Louisvdw** [comment]
Is this a new feature request or possible bug? I don't see any details except the heading.

**Comment by merlep** [comment]
It seems that Midpoint deviation as implemented on a BMV 702 is an unsigned number ie always above 0 . With the ddbus implementation ( which I guess is supposed to mimic the BMV implementation )  I see both positive and negative numbers reported to VenusOS remote console.  I say "seems"  as the Maths given in Victron datasheet does not indicate its an absolute number , however their description on  setting up an alarm in the handbook indicates its can only be a positive number. Furthermore I have only ever seen a positive deviation on my system having had several battery batteries in the past

**Comment by merlep** [comment]
I made a statement , not sure if you can see it on not. Basically how Victron implements deviation and how its done on dbusSerialdriver is slightly different . Victron implementation is unsigned whilst in dBusSerialdriver it is signed. Not a big deal , just how one implements an Alarm Rule for deviation  on VRM is slightly different

**Comment by mr-manuel** [comment]
Sorry, but I can't understand it neither.

1. You are saying that basically it's working, but it should be implemented like Victron does?
2. You saw, that the midpoint deviation sometimes was calculated negative by `dbus-serialbattery` and it should always be positive?

I could add `abs()` to the midpoint deviation to unsign the value.

**Comment by merlep** [comment]
You cannot have a negative deviation by definition is always a positive
number - just but an ABS function after your calculation

**Comment by mr-manuel** [comment]
A fix will be released with the next version.
