### ISSUE TITLE
v0.14beta2_WFech CCL/DCL considering cell-voltage and temperature

### ISSUE THREAD

**Issue by DirkReudenbach** [Louisvdw/dbus-serialbattery#316]
Hi 
I just installed the upper mentioned beta 2 version of Waldemar. 
I´m running 2 JK BMS on Victron ESS with Cerbo GX

Louis 14.1 beta version gives the option of more than one VRM instances and I could see both BMS with all graphs in VRM. Updating on Waldemars beta 14.2 version I still can see both BMS in Cerbo but with the same VRM Instance no (1)- so I lost the possibility to follow the VRM data for both BMS.

Could you please investigate?

Thanks

Dirk

**Comment by Louisvdw** [comment]
Update to the newly released v0.14 version. That should have all the previous fixes included
