### ISSUE TITLE
Settings in utils.py MAYBE not working as expected in V0.14

### ISSUE THREAD

**Issue by kakariki1** [Louisvdw/dbus-serialbattery#321]
I think I found another small issue.

Description:
Cell Voltage limitation enabled:   CCCM_CV_ENABLE   = DCCM_CV_ENABLE   = True
Temperature  limitation disabled: CCCM_T_ENABLE     = DCCM_T_ENABLE      = False
SOC limitation disabled:              CCCM_SOC_ENABLE = DCCM_SOC_ENABLE = False

Although SOC limitation is disabled, at least following parameters are taken into account when calculating min/max charge/discharge current/voltage values:
MAX_CELL_VOLTAGE, MAX_BATTERY_CHARGE_CURRENT, MAX_BATTERY_DISCHARGE_CURRENT

Not sure if this is the expected behaviour, at least according to the Wiki it should behave different:
You can set CCCM limits for 3 attributes which can be Enabled/Disabled and adjusted by settings in utils.py
-> The smallest limit from all **ENABLED** will apply.

Best regards,
lakeroe

**Comment by Louisvdw** [comment]
Thank you submitting.
This one is actually as it is intended so it is not a bug.

When all limitation attributes are disabled the battery still need to know how it should be set up. This is coming from these 3 attributes.
