### ISSUE TITLE
JK BMS Temperature problem below 0°

### ISSUE THREAD

**Issue by Knedox** [Louisvdw/dbus-serialbattery#339]
Hello,
now that we have negativ temperature in germany i have seen that my battery reports 0°C then 50°C then 100°C and then 0°C

So it seems like the negative temperature calculation here is wrong.
https://github.com/Louisvdw/dbus-serialbattery/blob/4157bd5dbe44c0bb4876f206af9ad810fdc339b2/etc/dbus-serialbattery/jkbms.py#L88

I was already able to find this out:

0x02 = 0b10      -> 2°C
0x01 = 0b1       -> 1°C
0x00 = 0b0       -> 0 °C
0x32 = 0b0110010 -> 0 ?
0x64 = 0b1100100 -> -1 °C
0x65 = 0b1100101 -> -2 °C
0x66 = 0b1100110 -> -3 °C

does anyone have the same problem? i am not really sure how to handle the 0x32 byte. Seems a little bit out of order

possible fix

    
temp1 = 0 if temp1 == 50 else temp1
temp2 = 0 if temp2 == 50 else temp2
self.to_temp(1, temp1 if temp1 < 100 else 99 - temp1)
self.to_temp(2, temp2 if temp2 < 100 else 99 - temp2)

**Comment by kakariki1** [comment]
According to the protocol definition here (https://github.com/jblance/mpp-solar/issues/112#issuecomment-850585642) the part exceeding 100 is negative temperature, such as 101 is negative 1 degree.

So I think the problem is here:
https://github.com/Louisvdw/dbus-serialbattery/blob/4157bd5dbe44c0bb4876f206af9ad810fdc339b2/etc/dbus-serialbattery/jkbms.py#L88

This should be changed to:
self.to_temp(1, temp1 if temp1 <= 100 else temp1 - 100)

Best regards,
lakeroe

**Comment by wormsman** [comment]
Many thanks for you fix and the protocol definition. I have changed it online on my installation. Currently my battery is at +1°C, so maybe I can see if the temperature reading is Ok with the change.

**Comment by kakariki1** [comment]
I made a mistake above. If it helps at all, the change has to be made to:
self.to_temp(1, temp1 if temp1 <= 100 else -(temp1 - 100))

In theory there should be no difference to the original code though ...

**Comment by MS123uk** [comment]
how do you make this change to the scraped ?  I'm new programming rasp and vinos os

**Comment by kakariki1** [comment]
Sorry, I'm no native english speaker.
What do you mean by "change to the scraped" ?

**Comment by MS123uk** [comment]
i have same problem with  jk bms showing the wrong temp below 0 c or 32f  i.e. 100 c  when bms probe go below 0c 
you 
This should be changed to:
self.to_temp(1, temp1 if temp1 <= 100 else temp1 - 100)

how  i  change this line

**Comment by kakariki1** [comment]
No I understand, just read here (How to edit utils.py):
https://github.com/Louisvdw/dbus-serialbattery/wiki/How-to-install#how-to-edit-utilspy

**Comment by MS123uk** [comment]
thanks

**Comment by MS123uk** [comment]
ok  can not find  line 88  self.to_temp(1, temp1 if temp1 <= 100 else 100 - temp1)  ?

**Comment by Knedox** [comment]
Well, now there is a copy & paste mistake in the code. Please check temp2, line 89

**Comment by wormsman** [comment]
Also the fix was not working for me. Via Bluetooth I got -0°C as current temperature and with the code in version 14.2 I got 100°C.

For me 

        self.to_temp(1, temp1 if temp1 < 99 else (100 - temp1))
        self.to_temp(2, temp2 if temp2 < 99 else (100 - temp2))

seems to work. I now get 0°C and hopefully can check this night some values below 0°C.

**Comment by Knedox** [comment]
> Also the fix was not working for me. Via Bluetooth I got -0°C as current temperature and with the code in version 14.2 I got 100°C.
> 
> For me
> 
> ```
>     self.to_temp(1, temp1 if temp1 < 99 else (100 - temp1))
>     self.to_temp(2, temp2 if temp2 < 99 else (100 - temp2))
> ```
> 
> seems to work. I now get 0°C and hopefully can check this night some values below 0°C.
> 
> I have tested the temperature sensors now with and salt ice bath and my fingers. In the range from -16°C up to 30°C the measurement with the formula above is correct and corresponds the data in the JK-BMS android software. In the android software I could see -0°C and also 0°C and booth were translated to 0°C.


i have tested your code. Seems to work:

![image](https://user-images.githubusercontent.com/31776618/209979884-5da48e46-7c35-42c4-a611-21680ceb9e03.png)
