### ISSUE TITLE
VRM and remoteconsole shows the current oposite

### ISSUE THREAD

**Issue by koch2907** [Louisvdw/dbus-serialbattery#349]
### Discussed in https://github.com/Louisvdw/dbus-serialbattery/discussions/348

<div type='discussions-op-text'>

<sup>Originally posted by **koch2907** December 13, 2022</sup>
Hello, please can you help me. 
i download the venus-data.tar.gz on 7.12.2022 it was the newest version.
I copied it to a microSD card and put it in the Cerbo GX. then i restart the GX.
it installed the Venus automaticly and i could see the batteries in the Remoteconsole and VRM. 
until here all was fine.

But now the problem. 
in the Daly BMS it shows me correct the current. Charge is + and discharge - 
In VRM and Remote Console when i start charging the batterie it shows me discharging and - and oposite.
![2022-12-08 12_16_18-Window](https://user-images.githubusercontent.com/120515265/207433876-41ea13d5-4cd0-4e65-a4d5-b382ee46fbec.png)
![2022-12-08 12_24_25-Window](https://user-images.githubusercontent.com/120515265/207433879-1d3ac707-dd75-485c-aeeb-3c5de64572d2.png)
![2022-12-08 12_24_56-Window](https://user-images.githubusercontent.com/120515265/207433882-8a41d11d-ef14-4d62-bc90-535eec1c465e.png)

Also i found that the installed capacity of the batterie in the Remoteconsole is only 50Ah and not 280Ah.
![installed and available capacity](https://user-images.githubusercontent.com/120515265/207434794-76c7881f-da56-46c1-9d01-afd63bbf3655.png)

The chargevoltage limit, charge current limit and dischargecurent limits are also wrong. 
in the Daly BMs i adjust the max charge current to 140A and the max discharge current to 280A
![chargecurrent dischargecurrent](https://user-images.githubusercontent.com/120515265/207435542-ae871f86-9505-47b0-94c3-b00afa265a43.png)
![DalyBms adjusted](https://user-images.githubusercontent.com/120515265/207437322-78270f97-1436-4970-a903-99aa96d19dbd.png)

please can you create a new Venus-Data.tar.gz file with the correct setting. 

</div>

**Comment by Louisvdw** [comment]
Some models of Daly BMS have the current that they publish swopped.
To show it correctly you need to edit utils.py and change it to -1 like this:
> INVERT_CURRENT_MEASUREMENT = -1
