### ISSUE TITLE
Problem with high battery temp- low temp alarms and sinowealth driver being picked up

### ISSUE THREAD

**Issue by MS123uk** [Louisvdw/dbus-serialbattery#352]
9.1 venous Os rarsp 4       JK bms  B2A8   with  UART  to RS485 JK converter  to wave  RS485  to usb  210Ah  24v  

   isolated 4 way usb port and Ve direct leads as show on off grid garage try this to day  and same problem shown high battery temp- low temp - and so on and  driver for bms  that`s not plug in shown device list 

_Originally posted by @MS123uk in https://github.com/Louisvdw/dbus-serialbattery/issues/296#issuecomment-1353247020_

**Comment by Louisvdw** [comment]
Can you clarify please.
Are you saying there is a problem with the temperature?

**Comment by MS123uk** [comment]
No if i use other type comm leads between rarsp 4  and smart shunt - solar controller and inverter all vitron alarm show  high battery temp- low temp - and so on and driver for bms that`s not plug in shown device list . Victron Ve direct usb leads are the only ones will work  but isolated 4 way usb port and Ve direct leads as show on off grid garage work fine on house solar system  Victron and rarsp  to  

only way  clear  the alarms is reboot

**Comment by MS123uk** [comment]
![image](https://user-images.githubusercontent.com/118858054/208238019-1b7c74da-c439-43e9-9020-0dc5c7bf7c4c.png)

**Comment by coca7** [comment]
I have seen similar alarms to MS123uk.  I also use a USB hub.  I mostly ignored it because I wasn't sure how to further isolate the problem and I knew the values were false.

**Comment by MS123uk** [comment]
And serial battery ( Sino wealth ) bms driver  will appear in your devices list in remote Console

**Comment by Louisvdw** [comment]
If you update to the latest v0.14.* then the Sinowealth driver has been disabled by default. This should prevent it from being picked up and giving false values.

**Comment by MS123uk** [comment]
thanks
