### ISSUE TITLE
Undervoltage alarm - why?

### ISSUE THREAD

**Issue by lennycb** [Louisvdw/dbus-serialbattery#363]
**Describe the bug**
Are those low voltage alarms coming from your driver.
I had asked this question before, at first glance it is obvious that the multi issues the alarm.

But there are not many places where I can specify values.
had already turned the settings down.
DC input low turn off: 40.8V
DC input restart: 41.8V
DC input low pre-alarm: 41.8V

In the ESS Assistant:
Sustain voltage: 45.0V
dynamic shutdown: all 4 values at 46V

None of these settings explain why an undervoltage alarm occurs above 52V.

The MIN/MAX cell voltages in the VRM look quite strange.
almost 12V max cell voltage or min below 1V. The BMS should have protected that.

However, no such entries can be found in the BMS log.
All voltages around 3.29V.

can you explain that?

**Expected behavior**
no error message

**Screenshots**
![image](https://user-images.githubusercontent.com/23618370/208710608-07e989d7-73da-4837-9134-09a3a3deb6ce.png)
![image](https://user-images.githubusercontent.com/23618370/208710709-147f10de-6704-4a40-93f2-30ac8cf3f5bf.png)
![image](https://user-images.githubusercontent.com/23618370/208710814-9131c868-1502-4560-991a-902617faf071.png)
![image](https://user-images.githubusercontent.com/23618370/208711144-ae4f2b97-f609-4354-9297-f5f7da5c798e.png)

**VenusOS (please complete the following information):**
 - Device type: Raspberry Pi4
 - Firmware Version v3.00~8

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: Daly 400A
 - Cells: 16x EVE 280Ah
 - Interface: USB-RS485

**Comment by lennycb** [comment]
I'm now back to v0.13 for testing purposes. Since then no alarms.

**Comment by lennycb** [comment]
> Ich habe ein ähnliches Problem und habe bereits herausgefunden, dass es wahrscheinlich mit der Einstellung CELL_VOLTAGES_WHILE_DISCHARGING in utils.py zu tun hat. Wenn die Gesamtbatteriespannung nahe oder unter nr_of_cells * CELL_VOLTAGES_WHILE_DISCHARGING[0] liegt, tritt die obige Warnung oder der Alarm auf. Ich habe die eigentliche Ursache noch nicht gefunden, aber ich bin mir ziemlich sicher, dass es sich um dasselbe Problem handelt.
> 
> Mit freundlichen Grüßen, Lakeroe

not so with me. I also get low voltage alarms at 52.82V. Since I have well balanced cells, that's about 3.3V per cell.

**Comment by e-i-k-e** [comment]
Having the same problem, use Daly BMS.

**Comment by HotteX** [comment]
I have similar issues, but for me it's "Low SOC" for certain cells, even though all of them have the same SOC and are around 3,2V. I tried to lower the lowest voltage to 2,6V without effect and the cells never could have dipped below 2,7V otherwise my BMS would have kicked in. 

The little number next to the date on the right shows the cell that has triggered the alarm right? 
If so, thats super-weird, because the cells causing my alarms are 9,10 and 19. But I only have 18 cells. (and all my systems only show 18 cells...there is no faulty wiring, I think).

**Comment by Louisvdw** [comment]
Those alarms that are raised show which service raise them. It is in that first line of the alarm shown in Remote Console like I show here. 
![image](https://user-images.githubusercontent.com/26077665/211391107-0e7721db-7e43-44c2-8600-a4e5689e3a15.png)
In this case the driver raised the alarm and you can investigate it from there.

For Multiplus alarms you need to look at the settings in the Multiplus. There are spesific settings that is set on the Mutiplus when it is commisioned which include the charging graph and this is what I expect is raising the Multiplus alarms. The only way I know how to set those are with a USB-MK3 dongle and the Ve.Configure. You can see those settings in screenshot in #371 

For the SOC alarm you first need to check who is raising the alarm. If it is not the driver then check what you have as the Battery Monitor of your system as it should be the one raising the alarm. SOC is a value for the hole battery and is not per cell.

**Comment by HotteX** [comment]
Thank you for the clarification. 
I was lead astray because of the little numbers in the corner as in the picture. I guess thats the SOC in %? Its always 19,10,9 or nothing in my messages. 
SOC_LOW was 20/10, so I guess, my issue is no issue, but to me the notification has a strange behaviour. 
I lowered the SOC_LOW values and see if it changes the messages. 

![IMAGE 2023-01-10 10:35:39](https://user-images.githubusercontent.com/67420589/211515640-459aafc0-f629-49e5-8fdf-0b4054cdb851.jpg)

**Comment by Louisvdw** [comment]
The default settings will give a low SOC warning at 20 and an alarm at 10. So that is what you are seeing.

**Comment by mr-manuel** [comment]
For MutliPlus settings see https://github.com/Louisvdw/dbus-serialbattery/issues/371.

**Comment by mr-manuel** [comment]
Another similar issue https://github.com/Louisvdw/dbus-serialbattery/issues/407

**Comment by brunnema** [comment]
Anyone checking this issue out >>> the Alarm will be reached where I assume that DCL - discharge control limit will report =0A to stop discharing... may you can check this there is in your graphs no battery activity anymore.

I descriebed it more detialed in the `https://github.com/Louisvdw/dbus-serialbattery/issues/407` Thread while I'm facing issues with charge /discharge toggling and getting the alarms.#

BR MArtin
