### ISSUE TITLE
VenusOS no web interface if # INVERT_CURRENT_MEAUREMENT = 1

### ISSUE THREAD

**Issue by e-i-k-e** [Louisvdw/dbus-serialbattery#366]
Hello everyone,

I just updated to the current 0.14.2
VenusOS 3.00~8
DalyBMS
Raspberry Pi 3

If I set "INVERT_CURRENT_MEASUREMENT = -1" back to = 1, I don't get any graphical interface from VenusOS. As soon as I go back to =-1, everything is okay again.

**Comment by huskyte** [comment]
I just add myself as I think this the solution to my issue. My measured charge to the battery adds to DC loads. Shouldn't it be the athoer way around? Couldn't find anything in the FAQ. DalyBMS 4S.

**Comment by Louisvdw** [comment]
@e-i-k-e can you post the serialbattery log file for when it fails with the -1 value.
https://github.com/Louisvdw/dbus-serialbattery/wiki/Troubleshoot#check-the-log-files-on-your-gx-device

**Comment by mr-manuel** [comment]
Is fixed with the next release.
