### ISSUE TITLE
MES PS5120E no BMS Communication

### ISSUE THREAD

**Issue by EKLAR** [Louisvdw/dbus-serialbattery#367]
Hello,

we have Installed MES PS5120E Batterys ( 16S ) the Cerbo detecd this Batery as an Pylontech,
the the Pylontech is an 15S Battery and the MES is a 16S Battery, this is the Problem we have.

We want to in crease the Charge Voltage in the Cerbo.

Please we can we do this?

Or is a other Solution, for this Battery?

**Comment by Louisvdw** [comment]
Hi
If this battery is detected as a Pylontech, then it is using the standard Victron CANbus implementation and not this serial driver. So  you will have to contact Victron or the battery supplier.
This driver does not support Pylontech batteries.
