### ISSUE TITLE
Victron beta v3.00–14

### ISSUE THREAD

**Issue by DirkReudenbach** [Louisvdw/dbus-serialbattery#368]
Victron released yesterday a new beta version which supports much more 3rd party batteries.
Updating to this version showed much more details in the JK BMS fields in Victron but all solar chargers showed "Error 67"
BMS could be seen in CerboGx 

I'm sure you are working already on a further development on this new release 

Regards

Dirk

**Comment by testpaul999** [comment]
@DirkReudenbach 
Is this issue persistent or did you find a solution?
I‘ll update to 3.00-14 but at the moment I wait.
Regards

**Comment by DirkReudenbach** [comment]
on my site v3.00-14 doesn't work and I could not find a solution on my site

**Comment by testpaul999** [comment]
Have done the update to 3.00-15
There are many new switches like switch „on/standby“ if I activated all it runs fine.

**Comment by e-i-k-e** [comment]
So do I understand this correctly, if the switch is activated on/standby, does the driver work as usual?
Can anybody confirm this? (which version?)

**Comment by testpaul999** [comment]
@e-i-k-e 
Sure have run the 3.00~14 and also the ~15 with the last public version of serialbattery.

**Comment by mr-manuel** [comment]
@e-i-k-e does the issue still persist?

**Comment by e-i-k-e** [comment]
> @e-i-k-e does the issue still persist?

No, it Work.

**Comment by mr-manuel** [comment]
@DirkReudenbach is it's also working for you please close this issue
