### ISSUE TITLE
DCL is "jumping" - should be 0 ?! - JKBMS

### ISSUE THREAD

**Issue by MisterX1000** [Louisvdw/dbus-serialbattery#371]
**Describe the bug**
In the utils.py (file is attatched) I set the DCCM current settings to "0A" when cell voltage reached 2.90V. 
The "SOC limitation" is disabled (False)

Now I have the problem that when this limit is reached and one cell is <= 2.90V, the discharge current starts jumping. And instead of switching the discharge off, the MP2-GX begins with charging the battery, then goes to "idle", then to "discharge" and so on.

While this happens there are many, many "Low battery: Alarm" messages from the VE.Bus System 275.
All the MP2-GX settings which could cause this are below this voltage levels and should not trigger any alarm. 
The DVVC is switched ON.

Maybe I did somenthing wrong in the serialbattery config file or I missunderstand something.

**Expected behavior**
I would expect that the current goes down to 0A when the voltage limit of <= 2.9V is reached. I don´t expect that the battery is reloaded with AC-grid power in the middle of the night when there is no sun.

**Screenshots**

**VenusOS (please complete the following information):**
 - Device type: MP2-GX
 - Firmware Version: 3.00 ~14, (v498)
 - Serialbattery version 0.14.2

**Battery/BMS**
 - BMS/Battery type: JKBMS / CALB LiFePo4 cells
 - Cells: 16
 - Interface: RS485 -->USB (MP2-GX)

**Additional context**

**MP2 & ESS settings; VRM graphs:** [all settings.pdf](https://github.com/Louisvdw/dbus-serialbattery/files/10313886/all.settings.pdf)
utils.py: [utils.txt](https://github.com/Louisvdw/dbus-serialbattery/files/10313795/utils.txt)

Alarm log: ![MP2_alarmlog_low-battery](https://user-images.githubusercontent.com/112106667/209802761-2b1b3754-8548-4230-8f69-c64fc24958e6.jpg)

VRM DCL graph: ![VRM_DCL-limit_vs_cell-voltage](https://user-images.githubusercontent.com/112106667/209802938-8c4f284d-3852-4a6b-b572-f87fddc7ef14.jpg)

![image](https://user-images.githubusercontent.com/112106667/209803930-456f8bff-8c31-4171-aa18-4939bd569777.png)
![image](https://user-images.githubusercontent.com/112106667/209803946-a45816b0-2ea8-4fbd-8eec-37304da42621.png)
![image](https://user-images.githubusercontent.com/112106667/209803975-1bfddd66-1d62-4058-9309-f20652e7965f.png)

**Comment by Louisvdw** [comment]
We'll have to improve the algorithm by adding a release voltage as well. 
What is happening is that as soon as no more current is drawn the cell values starts to recover  and the BMS release 
(the charger should only kick in when you are below the Min Soc value you have set in the ESS settings)

**Comment by MisterX1000** [comment]
Hey Louis,
thank you very much for your reply and for your great work here.

Maybe I can set the "sustain voltage" in ESS a little bit higher than the smaltest "DCCM_CV" cell voltage x16. Maybe this prevents the cells from discharging before the 0A voltage is reached and activates the sustain voltage like set in ESS.

Can you tell me if all the voltages which I set in the ESS (with VE Configure) are still counting, when your driver is installed?
I wonder which of the ESS settings have a higher prioroty then the settings in the utils.py?!

Thanks again for your help an great work. I wish you a happy new year.
Best regards
Alex

**Comment by Louisvdw** [comment]
The Limit values you set in DVCC always override everything. 
If those are not set then the CVL, CCL, DCL that you see under the Parameters section of your battery in the GX is derived from the settings in utils.py and will apply.

**Comment by MisterX1000** [comment]
Hey Louis,

I will try this and increase the "sustain voltage" - but this is not a setting in the DVCC, this is a "normal" setting in the VE configure. I attach a screenshot.

Best regards
Alex

<img width="476" alt="image" src="https://user-images.githubusercontent.com/112106667/210065113-5c3c0922-855e-4159-b25f-a8dcd098dd2e.png">

**Comment by MisterX1000** [comment]
Hey Louis,
unfortunately it didn't work to reduce the "Sustain-Voltage" value to 48V in the ESS assistant of the MP2.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/112106667/210218204-1ee4965f-37ff-45c0-9e80-22b8831f109a.png">

In the DVCC section I cant set anything which could help me here. There is no setting for a minimal voltage, only in the ESS assistant.

![image](https://user-images.githubusercontent.com/112106667/210217973-5fb75358-a1e7-4fd8-8fa9-1a11afab7ff9.png)
![image](https://user-images.githubusercontent.com/112106667/210218010-5f5ff17b-a454-482d-98bb-bece7e76261b.png)

The battery voltage is still dropping to the value which is set in the utils.py (2.9V) and then it begins to jump between charge-discharge-idle and so on.

I there something more I could do? Is this am JKBMS problem (or MP2-GX) only?

Thank you very much for your help!
Alex

<img width="790" alt="image" src="https://user-images.githubusercontent.com/112106667/210217540-f8afabbe-b9f0-4993-82f7-25d3abcc4874.png">

**Comment by MisterX1000** [comment]
> Hey Louis,
> 
> I will try this and increase the "sustain voltage" - but this is not a setting in the DVCC, this is a "normal" setting in the VE configure. I attach a screenshot.
> 
> Best regards Alex
> 
> <img alt="image" width="476" src="https://user-images.githubusercontent.com/112106667/210065113-5c3c0922-855e-4159-b25f-a8dcd098dd2e.png">

Just for information. 

What helped me here was reducing the Cut-off voltages in the ESS asisstant (there are 4 voltages for different currents) - when the battery voltage dropped to this cut-off voltage, the discharging will stop and the "sustain voltage" will jump in until the battery voltage rises up over the "above-cut-off" value.

Important!!! - When the ESS asisstant is activated, all the 3 low-voltage voltage settings under the "Inverter" tab are completely ignored by the MP2.

Best regards
Alex

**Comment by mr-manuel** [comment]
@MisterX1000 do I understand correctly, that your issue was solved? If yes, then I will add this to the FAQ.

**Comment by MisterX1000** [comment]
> @MisterX1000 do I understand correctly, that your issue was solved? If yes, then I will add this to the FAQ.

Hey mr-manuel,
for me the issue is solved. I think there are 2 ways to prevent this jumipng:
1. Current setting >0 (but I did not test this)
2. Reducing the ESS "Cut-off voltage" like I mentioned above

Thank you for your great support here!
