### ISSUE TITLE
ANT BMS Discharge / Charge Mosfet Switching 

### ISSUE THREAD

**Issue by lucasimons** [Louisvdw/dbus-serialbattery#40]
I would like to ask, if you could support for switching on / off the FETs from ANT BMS?

With the bluetooth , i can turn them on or off with the app.

Id like to disconnect the whole battery on low SoC for example to save energy in critical situations.

**Comment by pau1phi11ips** [comment]
Think this is pretty much a duplicate of issue 26

**Comment by mr-manuel** [comment]
Is this still wanted? Who would be available to give me access to his system to test?
