### ISSUE TITLE
JKBMS Consumed AmpHours not provided via Modbus from Venus

### ISSUE THREAD

**Issue by lyncker** [Louisvdw/dbus-serialbattery#401]
**Describe the bug**
Im not sure, if this is a bug or a missing feature;) 
I connected my JKBMS with this lib , thanks for the good work !! 
Inside the Venus I get all the values like SOC and ConsumedAmpHours from the Batterysystem (JKBMS). 
But if I try to read the Modbusregisters like 845 or 265 from another system the CalculatedAmpHours is always 0 while f.e the SOC Value is transmitted correctly ... 

With dbus-spy I can see that the value ConsumesAmphours is also available ... 

Thanks for Help 

**To Reproduce**
Read the ConsumedAmpHours Register 845 using Modbus

**Expected behavior**
the Value should be provided
**Screenshots**

**VenusOS (please complete the following information):**
My Venus is the last one V2.92 Build 20221016213031 (RASP3)

**Battery/BMS (please complete the following information):**
JKBMS S16

**Additional context**

**Comment by mr-manuel** [comment]
This sounds like a bug in Venus OS, since this driver is only publishing the values to the dbus. Please post a question in the [Victron Community](https://community.victronenergy.com).
