### ISSUE TITLE
PageBatteryCellVoltages showing on Victron Shunts page

### ISSUE THREAD

**Issue by vincegod** [Louisvdw/dbus-serialbattery#408]
The gui modifications for dbus-serialbattery are displaying on the Victron Shunts battery page and should be hidden.

![image](https://user-images.githubusercontent.com/6048606/212209626-77651348-6446-47af-8ea2-a32b0f868196.png)
![image](https://user-images.githubusercontent.com/6048606/212209846-4c175bd1-21e9-4432-99bc-a03fdce5c9d8.png)

**Comment by mr-manuel** [comment]
Which Venus OS version are you using?

**Comment by mr-manuel** [comment]
Please see https://github.com/Louisvdw/dbus-serialbattery/issues/469. This issue is fixed in the next version.
