### ISSUE TITLE
Only allow merge if CI is green

### ISSUE THREAD

**Issue by ppuetsch** [Louisvdw/dbus-serialbattery#413]
I suggest to protect the master branch in the GH-Settings and only alow PRs to be merged if all GH Actions are green.

**Comment by Louisvdw** [comment]
@ppuetsch 
Is there a way I can run those action manually on a branch before a PR is approved. 
Or will setting change force the user create the PR to run those actions first?

**Comment by mr-manuel** [comment]
@ppuetsch maybe you know this?
