### ISSUE TITLE
Possibility to Contribute to Documentation

### ISSUE THREAD

**Issue by ppuetsch** [Louisvdw/dbus-serialbattery#414]
Currently, the documentation lives as Wiki. This is a bit unfortunate, as one can't contribute to that easily. 

One solution might be to copy over the documentation into the repository itself. Then 
a) One can adapt documentation along with code changes
b) has always the documentation that fits the currently checked out revision

What do you think?

**Comment by Louisvdw** [comment]
@ppuetsch that is a good idea.
I was planning to move the docs from the wiki to github pages. The markdown does have a few limitations what you can display. 
Do you think normal markdown docs inside the repo/branch will work better than github pages? We could also split it.
I'm open for suggestions, but I do want to expand the documentation with a bit more detail for each BMS type

**Comment by mr-manuel** [comment]
I have prepared a solution for this with Docusaurus, GitHub Actions and GitHub Pages. The source code of the docs will be in a folder of the repository and therefore also browsable by version.

**Comment by mr-manuel** [comment]
The documentation is now located in the source code in the folder `docs/docs` and is published automatically after new commits to https://louisvdw.github.io/dbus-serialbattery/
