### ISSUE TITLE
serial battery JKbms 0.14.3 show  #3  and # 4  

### ISSUE THREAD

**Issue by MS123uk** [Louisvdw/dbus-serialbattery#426]
serial battery JKbms driver V 0.14.3 show ess #3  and ess # 4  alarm  but   charge  and  discharge blocking
   has not showing  phone app 

JKBMS  S8  24v 

Charging
76 W
97.0 %
ESS #4
Voltage
27.02 V
Current
2.82 A
Temperature
1 °C
ESS #4
BMS disabled discharge

**Comment by Louisvdw** [comment]
can you show us your serialbattery log file?
https://github.com/Louisvdw/dbus-serialbattery/wiki/Troubleshoot#check-the-log-files-on-your-gx-device

**Comment by MS123uk** [comment]
login as: root
root@192.168.0.20's password:
Last login: Fri Dec 30 17:38:05 2022 from 192.168.0.5
root@raspberrypi4:~# /data/log/serial-starter/current
-sh: /data/log/serial-starter/current: Permission denied
root@raspberrypi4:~# /data/log/dbus-serialbattery.ttyUSB0/current where ttyUSB0 will be your USB port (ttyUSB0/ttyUSB1/ttyUSB2/etc.)
-sh: syntax error near unexpected token `('
root@raspberrypi4:~# /data/log/dbus-serialbattery.ttyUSB0/current where ttyUSB0 will be your USB port (ttyUSB0/ttyUSB1/ttyUSB2/etc.)/data/log/dbus-serialbattery.ttyUSB0/current where ttyUSB0 will be your USB port (ttyUSB0/ttyUSB1/ttyUSB2/etc.)

**Comment by mr-manuel** [comment]
Do the issue persist or did you solve it?

**Comment by MS123uk** [comment]
still not solve

**Comment by mr-manuel** [comment]
Could youbtry to install this version? https://github.com/Louisvdw/dbus-serialbattery/discussions/485

It's the most updated one.

**Comment by MS123uk** [comment]
have install  but now will show in device list

**Comment by mr-manuel** [comment]
Can you please explain better?

**Comment by MS123uk** [comment]
too start with installed this  wget -O /tmp/install-nightly.sh https://raw.githubusercontent.com/Louisvdw/dbus-serialbattery/jkbms_ble/etc/dbus-serialbattery/install-nightly.sh && bash /tmp/install-nightly.sh
and selected 2  for jk bms  and rebooted  but  driver did not show in VRN  and no conn between bms and raspberry i  so  fund new  web page https://louisvdw.github.io/dbus-serialbattery/general/install  and used this install and this now up running just trying to work out if its most upto date one

**Comment by mr-manuel** [comment]
You see the driver version in the log and in the GUI `SerialBattery` -> `Device` -> `Firmware version`.

**Comment by mr-manuel** [comment]
Did you troubleshoot, when the driver did not show? It did not show in the GUI or only in the VRM Portal?

It it's try for you to write englisch try deepl.com, it translates very well.

**Comment by MS123uk** [comment]
You see the driver version in the log and in the GUI SerialBattery -> Device -> Firmware version.

this is what its showing  in Serial Battery -> Device -> Firmware version.  0.14.3

**Comment by MS123uk** [comment]
GUI ?

**Comment by mr-manuel** [comment]
GUI/Remote Console

With `v0.14.3` you have the latest release, but not the latest up to date available version. See [Install over SSH: nightly version/beta test](https://louisvdw.github.io/dbus-serialbattery/general/install/#install-over-ssh-nightly-versionbeta-test) and then troubleshoot it it's not working.

**Comment by MS123uk** [comment]
when the driver did not show? It did not show in the GUI or only in the VRM Portal?

It did not show remote console or  VRM Portal device list

**Comment by mr-manuel** [comment]
P.S.: Instead of taking a picture of your screen, you can make a screenshot by pressing `Windows Key + Shift + S`, select what you want to capture and then paste directly in the text box of GitHub.

**Comment by MS123uk** [comment]
will do thanks

**Comment by MS123uk** [comment]
![Screenshot 2023-04-29 121830](https://user-images.githubusercontent.com/118858054/235299939-313978b3-7889-482c-a815-f6c65e915bc0.png)
password ?

**Comment by mr-manuel** [comment]
Just click the link in the manual or use the search.

![grafik](https://user-images.githubusercontent.com/12592765/235300436-ba3b2965-efd4-4c9b-aa4b-7a91915fde41.png)
