### ISSUE TITLE
Charger / Multiplus do not pay attention to Charge current limit

### ISSUE THREAD

**Issue by hoschult** [Louisvdw/dbus-serialbattery#445]
**Describe the bug**
- Charge current limit is set according to SoC to 10Amps and is reported correctly by vrm (see screenshot)
- However battery gets charged beyond this limit of 10 Amps by the victron RS450/100

**To Reproduce**
- Need to have an AC and DC coupled victron system with JBD bms --> see screenshot of plant topology
- Set DVCC to YES and use shared voltage / current sense
- Use serialbattery and the algorithm to reduce charge current in respect to SoC (Limit 10Amps when SoC >= 97%)
- In ESS, switch on AC and DC coupled PV feed in excess
- Let RS450/100 set under external control under BMS
- finally: Wait for a sunny day and observe that all power which is delivered from RS450 will be feed into battery (regardless charge current limit)

**Expected behavior**
I would expect that Venus will respect the charge current limit of JBD bms settings via dbms-serialbattery so that multiplus inverts all the power above 10Amps (coming from RS450) towards ACIn to grid for feed in

**Screenshots**

Overview about topology (at 12.19) where where charge current of 51.4Amps can be observed consumed by battery:

![image](https://user-images.githubusercontent.com/20515558/215753018-8d30e921-e736-41c4-ab69-87a25f527bf5.png)

Charge current limit in VRM which was rightfully adjusted in respect to SoC:

![image](https://user-images.githubusercontent.com/20515558/215753347-b17632a0-032f-4b6d-9809-d64dc21bdbda.png)

Current flow chart towards battery:

![image](https://user-images.githubusercontent.com/20515558/215753421-cdc608ad-75b8-4c46-b43d-d7405b131cf5.png)

Grid feed in settings of ESS:

![image](https://user-images.githubusercontent.com/20515558/215753470-a170dac7-c5e8-47ec-b6cc-987c29ef699a.png)

Networked options of Victron Charger (RS450/100):

![image](https://user-images.githubusercontent.com/20515558/215753538-a7c65f56-d40f-4033-9290-6394dfa1cc7a.png)

**VenusOS (please complete the following information):**
 - Device type: Raspberry Pi
 - Firmware Version: v2.92

** Bus-serialbattery is installed at 0.141

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: JBD
 - Cells: 16
 - Interface:
```
                      Battery --> UART --> Raspberry Pi (VenusOS) <-- VeDirect <-- RS450/100
                                                                                  ^
                                                                              VEBus
                                                                                  ^
                                                            3phase cluster Multiplus 5000
```

**Comment by wormsman** [comment]
As far as I know the Charge Current Limit is ignored from the MPPT when you have an ESS system and also DC Feed in activated. The question is why the multiplus do not feed in enough.

**Comment by hoschult** [comment]
Hi wormsman, thx for pointing this out.  

> "The question is why the multiplus do not feed in enough"

Yes, exactly this are also my thoughts.... By hunting for answers I tumbled about this victron community posts: https://community.victronenergy.com/questions/91148/dvcc-limit-charge-current-not-working-with-grid-fe.html

I'm not quite sure in which direction to continue to search because it might be also an issue/bug which comes directly out of victron's ESS algorithm...

**Comment by hoschult** [comment]
Hi all,

my system is now working with dc feed in and is respecting charge limits (CCL). The solution was to reduce voltages in utils.pl to:

```
MAX_CELL_VOLTAGE = 3.42                                                                                                
FLOAT_CELL_VOLTAGE = 3.37  
```

I think to lower the voltage of the DC-Charger (RS450) let the Multiplus to be able to transport current towards AC since battery not catches all the power (due to voltage spread charge voltage / battery voltage):

![image](https://user-images.githubusercontent.com/20515558/217889026-1a66e440-6c5f-4cd9-9537-b131b7730efe.png)

**Comment by LarsAndersenDenmark** [comment]
Hi
Lowerig only helps stop charging earlier. The CCL is as far as I have experienced not accepted by what you are doing.
Could some coding in the Dbus battery help controlling the charge level some how? Maybe by setting a dynamic CVL based on the actual charge current seen, since the MPPTs still respect the CVL.
