### ISSUE TITLE
BMS / driver disconnected after reboot

### ISSUE THREAD

**Issue by teefixx** [Louisvdw/dbus-serialbattery#456]
**Describe the bug**
When I reboot the GX device (RBpi) Node Red does not find the source which I chose in the node. I need to reconnect manually all node in node red. It is odd, as the name is exactly the same:
- "SerialBattery(Daly) [disconnected]": this is selected but does not work anymore
-" SerialBattery(Daly)": This needs to be reselected to connect the node again

The error in the debug window: "TypeError: Cannot read property 'XXXXX' undefined"

So far I do not use custom naming as it is known, that the name is lost during reboot

**To Reproduce**
1. Reboot the GX device
2. Go to Node Red
3. All Connections to the BMS Nodes (Victron Battery Monitor) are red
4. Open each Node and reconnect it 

**Expected behavior**
No necessity to recconnect nodes

**VenusOS (please complete the following information):**
 - Device type: [e.g. Pi3]
 - Firmware Version [3.00-14]

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: [Daly 300A]
 - Cells: [16]
 - Interface: [USB-RS485]

**Additional context**

**Comment by mr-manuel** [comment]
@teefixx can I close this?
