### ISSUE TITLE
Performance Problems with > than 6 Batteries, exclude some

### ISSUE THREAD

**Issue by pos-ei-don** [Louisvdw/dbus-serialbattery#464]
My Raspberry 4 8gb gets very slow when
A lot of batterys are connected.
As I dont need All batteries on its own, but need their data
For a additional Aggregated battery (which I use per mqtt), I suggest excluding some or All batteries from showing in the console, but deliver their data for use in ess.

**Comment by Maxwell27321** [comment]
I have the same issue wie 4 banks, jk bms, connected to Cerbo GX via USB hub.

**Comment by transistorgit** [comment]
which bms types and which interface? I found a bug relating to Daly and RS485 in that combination that would lead to slow updating.

**Comment by pos-ei-don** [comment]
I read your progress with daly in the comments!
Unfortunately, I only use JK-BMS as they work best for me according to my tests.
I have a spare daly aswell, but don't like their balancing and i had the daly RS485 adapter getting hot and melting
which was no fun ;-)

**Comment by mr-manuel** [comment]
@pos-ei-don could you check what causes the load? What is the output of this command?

```bash
top -b -n 1 | head -n 23
```

Best would be, if you keep watching `top` for a few seconds to understand, if there are spikes that cause the problem.

**Comment by pos-ei-don** [comment]
Unfortunately, I cannot. I seperate the production-venusos  and one for testing. All batteries are not connected anymore, I only use your mqtt-battery on the production system for limiting Charge speed when the batteries are >55 Volts. And, I am not in the Country vurrently, so i cannot reconnect.
I can only say that my venusos is much more performant since then, and it is better in calculating settings. Also the gui is much faster.

**Comment by mr-manuel** [comment]
Would you investigate further when you are back or can I close this issue?
