### ISSUE TITLE
Charge and Discharge flickering (always jumps to 0) since driver is installed

### ISSUE THREAD

**Issue by MartinKutz** [Louisvdw/dbus-serialbattery#470]
**Describe the bug**
I had the Multiplus 2 running a week without connected BMS.
The charge and discharge behavior curve is in diagram 1.

Yesterday I installed the dbus-serialbattery driver and I can see all the Daly BMS values in VenusOS. But charge and discharge jumps always to 0.

**Screenshots**
[1] Charge/Discharge before:
![image](https://user-images.githubusercontent.com/17049656/220550130-cebfe658-5a96-430a-bfed-ce5b7698f365.png)

[2] Charge/Discharge after:
![image](https://user-images.githubusercontent.com/17049656/220550292-b7d6349a-bcb8-4fee-8207-36ce02533a5e.png)

**VenusOS (please complete the following information):**
 - Device type: Raspberry Pi 4
 - Firmware Version: 2.92

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: Daly BMS, LifePo4 Battery
 - Cells: 16
 - Interface: Uart

**Comment by mr-manuel** [comment]
Have you enabled or disabled this?

https://github.com/Louisvdw/dbus-serialbattery/blob/3685d15a5d1ba801867bbdb98f57fd805ea2c24a/etc/dbus-serialbattery/utils.py#L35-L38

Can you try what happens with `v0.14.2`?

**Comment by MartinKutz** [comment]
Thanks for your response!
LINEAR_LIMITATION_ENABLE is set to false. What is the recommendation to this setting?

Ok, I will try v0.14.2 in the next few days.

**Comment by mr-manuel** [comment]
Unfortunately I have no reccomendation for this setting, maybe someone other.

**Comment by MartinKutz** [comment]
@mr-manuel sorry, I had no time last weeks. I will have a try beginning of next week.

**Comment by mr-manuel** [comment]
Maybe also this can help you https://github.com/Louisvdw/dbus-serialbattery/issues/371.

**Comment by MartinKutz** [comment]
Today I had time to test it again.

I cannot get Version v0.14.2 to work.
This is my modified install script:
`
#!/bin/bash
set -x
curl -s https://api.github.com/repos/Louisvdw/dbus-serialbattery/releases/86212497 | grep "browser_download_url.*gz" | cut -d : -f 2,3 | tr -d \" | wget -O venus-data.tar.gz -qi -
tar -zxf ./venus-data.tar.gz -C /data
sh /data/etc/dbus-serialbattery/reinstalllocal.sh
`

With current version it's running.

Issue #371 has the flickering behavior only in the near of the cut of voltage - I have the flickering all the time at charging and discharging.

I reinstalled the newest version and for some reason I havn't the behavior anymore.
I will monitor it for the next days. But seems to work.

![image](https://user-images.githubusercontent.com/17049656/235634962-2c23845e-662c-4404-b6d7-c190d1430028.png)

Thanks for your help!

**Comment by mr-manuel** [comment]
With the latest code we changed a lot and fixed a lot of issues. Feel free to reopen the issue, if you see the same error again.
