### ISSUE TITLE
MP keeps charging and discharging at set point MAX_CELL_VOLTAGE

### ISSUE THREAD

**Issue by Joeknx** [Louisvdw/dbus-serialbattery#471]
Hello,

my Multiplus II keeps changing between charging and discharging at MAX_CELL_VOLTAGE = 3.45 (55.2)
Every 10 sec or so. 

Is this a normal behavior, or did I miss any settings?
Versions:
0.14.3
Venus 3.00-15

Thank you!

VenusOS (please complete the following information):

Device type: Raspberry Pi 3b+
Firmware Version: 3.00-15

Battery/BMS (please complete the following information):

BMS/Battery type: 
JK BMS, LifePo4 Battery
Cells: 16
Interface: RS485

**Comment by mr-manuel** [comment]
Something like that? https://community.victronenergy.com/questions/1976/ess-short-discharge-pulses-in-float.html

**Comment by Joeknx** [comment]
It doesn't say Float, but the problem seems the same. Maybe it is normal to keep the 55,2V

**Comment by mr-manuel** [comment]
In the OverView it doesn't say float? Have you checked the "Device List"?

![grafik](https://user-images.githubusercontent.com/12592765/220670078-d2f2d7a0-5908-4ded-b166-847c1f5bf791.png)

![grafik](https://user-images.githubusercontent.com/12592765/220670152-8893125b-3b7a-449f-a1b3-fb3558922a47.png)

**Comment by Joeknx** [comment]
The device list looks like yours and says absorption. 
The Amps from "SerialBattery(Jkbms)" flickers between "-" and "+" and in the VRM it changes between "Discharging" an "External control"

**Comment by Joeknx** [comment]
I'm not sure if you mean this:
<img width="432" alt="Bildschirm­foto 2023-02-22 um 17 48 11" src="https://user-images.githubusercontent.com/77569160/220709265-ea61ca23-fc14-4e0c-a990-54c533a324e0.png">
<img width="422" alt="Bildschirm­foto 2023-02-22 um 17 48 28" src="https://user-images.githubusercontent.com/77569160/220709319-eaadc79c-11d0-4ede-b67b-2352cec71281.png">
<img width="451" alt="Bildschirm­foto 2023-02-22 um 17 48 47" src="https://user-images.githubusercontent.com/77569160/220709351-08d63097-af31-44f7-a55f-7ca5093c747d.png">
<img width="461" alt="Bildschirm­foto 2023-02-22 um 17 48 54" src="https://user-images.githubusercontent.com/77569160/220709367-4802b4ca-449f-42e8-b210-a911ed953829.png">
<img width="454" alt="Bildschirm­foto 2023-02-22 um 17 49 04" src="https://user-images.githubusercontent.com/77569160/220709423-48f8d993-e82a-4cc5-b42f-1495776a26bd.png">
<img width="457" alt="Bildschirm­foto 2023-02-22 um 17 49 11" src="https://user-images.githubusercontent.com/77569160/220709470-138a4b96-3989-49a2-b762-97752ba4b1a8.png">
<img width="461" alt="Bildschirm­foto 2023-02-22 um 17 49 21" src="https://user-images.githubusercontent.com/77569160/220709499-a52bdd5a-918f-4b3a-a3df-582dcba11850.png">
<img width="454" alt="Bildschirm­foto 2023-02-22 um 17 49 27" src="https://user-images.githubusercontent.com/77569160/220709526-b55f1cab-418e-4507-8d8b-f655af6a09a9.png">
<img width="453" alt="Bildschirm­foto 2023-02-22 um 17 49 37" src="https://user-images.githubusercontent.com/77569160/220709557-ae67f3ff-5c4d-400c-a893-e23b2fc3fe05.png">
<img width="489" alt="Bildschirm­foto 2023-02-22 um 17 51 05" src="https://user-images.githubusercontent.com/77569160/220709600-23cb9337-0d04-4d06-852f-0ffde35ebc3d.png">

**Comment by pos-ei-don** [comment]
I have Float Set to 56.8V, Absorbtion to 57.8v, but stop charging using the serialBattery-settings at 55.2V, like as you did directly on the MPII.
And I set the Max charging voltage to 56.3v.
Seems wo work better in this case, but maybe settings can be improvend further.

**Comment by Joeknx** [comment]
Ok thank you. 
Maybe the MPII  and serialbattery are interfering. 
I try to change the Settings in the MPII tomorrow

**Comment by morres83** [comment]
I would also like to follow up on this topic, I think I have a similar issue.
I have deactivated current limits based on SoC (@Joeknx is it  the same for you?) because I think that the SoC from BMS is getting massively shifted when the battery is not being fully charged for about 12-14 days (currently not enough sun, the SoC is floating between 15-50% for the last 2 weeks.). Actually it says 15% but the voltage is so low that it more or less corresponds to 1-5%. This error also propagates to the full charging, meaning SoC is shown as 100% (I tested by charging from grid) but the voltage is too low (<3.4V). That was the reason that I deactivated limits on SoC and relied on charging limits based on voltage.

Now what happens is that it charged to 100% SoC (after the above mentioned 2 weeks of being betw. 10-50%) but the cell voltages are still so low that it keeps charging with 60A for 1-2 hours. I think it could be okay but the issue is that when one cell hits the limit (e.g. 3.45 V) the first current limit applies 60A-30A. 
-> Immediately the cell voltages drop (being below 3.45V)
-> The full current gets released again (30A->60A)
-> The cell voltages grow fast and hit the limit again , and so on
It seems being in a loop and I guess it is not how it should be.

The problem of this topic here sounds very similar.
So I fear that the charge controlling has to rely on SoC and this setting must not be turned off.

Anyone with a suggestion on it?

**Comment by Joeknx** [comment]
> The problem of this topic here sounds very similar. So I fear that the charge controlling has to rely on SoC and this setting must not be turned off.
> 
> Anyone with a suggestion on it?

Yes, @morres83 I also have deactivated charging based on SOC.

But my "problem" is different. Only the inverter changes pretty quick between charging and discharging but keeps 55.2V
My guess is, the this is the normal behavior to keep the limit!?

Are your Cells balanced? Sound like they are not.

<img width="1155" alt="Bildschirm­foto 2023-02-23 um 13 26 19" src="https://user-images.githubusercontent.com/77569160/221649768-05b2c790-0b74-40f7-a74c-fa4d8878762c.png">

**Comment by morres83** [comment]
Yes my cells are balanced so this shouldn't be the problem. For me it seems that when the current drops, also the voltage drops. Maybe I have to wait a longer time until it settles, but today it wasn't possible because the sun was gone.

For reaching your 55.2V, did you charge a long time when it was showing already 100%?

**Comment by Joeknx** [comment]
It didn't take a long time. 
What I know is that when the Voltage drops when the current goes down, the Cells are not full!
So you probably have to wait a longer time.

What I noticed is that serial battery takes the MPII Voltage to limit and not the BMS Voltage. I have selected the BMS as battery monitor!
The Voltages were different so I saw it. Now I calibrated the BMS and it does not matter anymore.

**Comment by morres83** [comment]
I have also selected JKBMS as battery monitor, but it is an interesting point about the voltages. So you are saying you have calibrated the JK BMS to "see" the same voltage as the MP II? Currently they also differ for me (a bit):

![image](https://user-images.githubusercontent.com/10619650/221659482-2bb706ba-c791-42a5-a84e-e6478c921fd7.png)

![image](https://user-images.githubusercontent.com/10619650/221659518-5d874e51-3047-4361-a323-b1e75dea272b.png)

**Comment by pos-ei-don** [comment]
... But this Dr er can throttle the charging amps linear to cell voltage. So the should never be this on/off All the time, it should narrow the soc  to 100% slower and slower.

**Comment by morres83** [comment]
Hello @pos-ei-don , yes now when you are saying this, normally it should be linear. But I am very sure that there was never a linear interpolated value. The parameter either showed 60A or 30A (so current at 3.3V point or current at 3.45V point) and nothing in between. So I was digging around and I found that LINEAR_LIMITATION_ENABLE in involved here. I will try with this option turned on to get rid of the jumps.

What is CVCM_ENABLE, I am not sure about this one...

**Comment by pos-ei-don** [comment]
Sorry, nö. Unfortunately it seems that I mixed it up with an fork I once tried. So sorry, I cant help currently

**Comment by Bonzai10** [comment]
charging/discharging when the battery is full is normal. the driver does not go into float mode under linear.

test the version 0.14 version. This works for me, I think 0.14.3 has an error in this regard.
Values are taken from the SOC calculation although linear is set.

**Comment by seidler2547** [comment]
I think one of the things that would be important here is to reduce the current earlier. I set `LINEAR_LIMITATION_ENABLE` to `True` and I reduced the voltages in this table:
```
# Set Steps to reduce battery current. The current will be changed linear between those steps
CELL_VOLTAGES_WHILE_CHARGING         = [3.55, 3.48, 3.42, 3.30]
MAX_CHARGE_CURRENT_CV                = [   0,    2,  40,  80]
```
(Note that I want 80A max charging.) This way, the charging current is reduced early and there is a nice lowering charging curve towards the top:
![image](https://user-images.githubusercontent.com/729588/225571250-bb6dbafe-c03f-480e-8fc2-7e1ca36ed832.png)

In the rightmost graph, the orange line is the current limit imposed by the driver. You can see that even though it was 100% sunny today, the MPPT started throttling the charge as the battery got more full.

**Comment by mr-manuel** [comment]
> charging/discharging when the battery is full is normal. the driver does not go into float mode under linear.
> 
> test the version 0.14 . This works for me, I think 0.14.3 has an error in this regard. Values are taken from the SOC calculation although linear is set.
> 
> see here: #421

Is solved with the next version.
