### ISSUE TITLE
Cell tradings of Daly BMS

### ISSUE THREAD

**Issue by DIVERSDIVERS** [Louisvdw/dbus-serialbattery#514]
Hi, 

i can not see single cells ins Venus OS.
(diver support for Daly BMS to track each cell)

My specifications:

BMS: Daly BMS 250/125 8S
BMS SW-Version: 11_220920_DK1T
BMS connection: via RS485 to USB
Cells: 8 cell configuration 
Diver Version: v 0.14.3
Venus OS Version: Color GX Venus OS v 2.93
Configuration: see attachment

[utils.zip](https://github.com/Louisvdw/dbus-serialbattery/files/11177249/utils.zip)

Thank you

**Comment by rbeudel** [comment]
Look here [https://github.com/Louisvdw/dbus-serialbattery/issues/397](url)

**Comment by DIVERSDIVERS** [comment]
i looked, thank you but where i have to do this changes?

**Comment by rbeudel** [comment]
[daly.zip](https://github.com/Louisvdw/dbus-serialbattery/files/11177372/daly.zip) It is the daly.py file in the same folder like the utils.py. Backup your daly.py and try the linked one.

**Comment by DIVERSDIVERS** [comment]
thank you very much it worked.

Last Question: is it possible to store the name, beacause after every reboot from Venus OS allways the same standard name "SerialBattery(Daly)"
![001](https://user-images.githubusercontent.com/129951689/230583860-e33932c2-013f-4cc5-8230-a0e905aa747c.JPG)
![002](https://user-images.githubusercontent.com/129951689/230583863-3ba48ba7-9ff0-4dad-871c-b3889496caa4.JPG)
![003](https://user-images.githubusercontent.com/129951689/230583864-b4b644e7-e11d-4ffb-896c-17f01a24f395.JPG)

**Comment by mr-manuel** [comment]
It is not yet possible to store the name. It's planned for the future.

**Comment by DIVERSDIVERS** [comment]
ok thanks for help for both

**Comment by mr-manuel** [comment]
Can probably be closed when https://github.com/Louisvdw/dbus-serialbattery/pull/484 is merged.

**Comment by mr-manuel** [comment]
Can probably be closed when https://github.com/Louisvdw/dbus-serialbattery/pull/484 is merged.

**Comment by mr-manuel** [comment]
If you want to close it already even better :)

**Comment by teefixx** [comment]
> thank you very much it worked.
> 
> Last Question: is it possible to store the name, beacause after every reboot from Venus OS allways the same standard name "SerialBattery(Daly)" ![001](https://user-images.githubusercontent.com/129951689/230583860-e33932c2-013f-4cc5-8230-a0e905aa747c.JPG) ![002](https://user-images.githubusercontent.com/129951689/230583863-3ba48ba7-9ff0-4dad-871c-b3889496caa4.JPG) ![003](https://user-images.githubusercontent.com/129951689/230583864-b4b644e7-e11d-4ffb-896c-17f01a24f395.JPG)

Hi

Can you tell me how you go rid of the fields you don't need, eg Bus voltage, Starter voltage, Top section voltage, ...
I see on your photos, that only the fields you need are displayed...

Thank you

**Comment by mr-manuel** [comment]
Probably you have Venus OS > 3.00~14. There is already a PR https://github.com/Louisvdw/dbus-serialbattery/pull/468 open to solve this. You can manually install a copy of the master branch from my fork, if you want to get rid of until the PR is merged.

**Comment by teefixx** [comment]
@mr-manuel 

I did that today, but after that the whole cell voltage block was missing…
Installed Venus Version: 3.00-21

**Comment by mr-manuel** [comment]
Because you have to apply the Daly fix after (https://github.com/Louisvdw/dbus-serialbattery/pull/484). It's not applied in my fork.

**Comment by teefixx** [comment]
This worked, thank you mr-manuel.
Do you plan to publish a release on github or will you stick to manual install?

**Comment by mr-manuel** [comment]
No, you will have to wait for the open PR to be merged.
