### ISSUE TITLE
Cell tradings of Daly BMS - Not updating

### ISSUE THREAD

**Issue by DIVERSDIVERS** [Louisvdw/dbus-serialbattery#516]
Sorry to bother you again, unfortunately it doesn't update the cell voltage

Single Cells (1-8) not updating.

Connected via RS485 to USB cabel

![001](https://user-images.githubusercontent.com/129951689/230617576-f496194e-d5e7-4249-a0e9-a00aae9d85df.JPG)
![002](https://user-images.githubusercontent.com/129951689/230617577-569fe1fa-5d09-494a-8e2d-de96277ec0ae.JPG)

**Comment by rbeudel** [comment]
[daly.neu.zip](https://github.com/Louisvdw/dbus-serialbattery/files/11179594/daly.neu.zip) I dont have changed all parameter like in #397
I did this and I hope it will be fine for you and I did not mistake. @towatai reported his 8s runs.

**Comment by DIVERSDIVERS** [comment]
thank u i tried it still not updating single cells, only one when i reboot
![Bild_2023-04-07_170820519](https://user-images.githubusercontent.com/129951689/230631958-f959595a-e0f3-4928-a422-0647ff614bf2.png)

**Comment by rbeudel** [comment]
Then I cant help you ;-)

**Comment by towatai** [comment]
What Type of Cable is used? A original Daly? i´ve switched back to the UART ---> USB Cable because the RS485 make Problems together with Aggregate Batterys as descriped in #397
I only use original Daly-Cables!

**Comment by DIVERSDIVERS** [comment]
original Daly RS485 to USB

**Comment by transistorgit** [comment]
Hi, the problem is because of bugs in the serial interface programming for daly devices. I fixed it in the pull request https://github.com/Louisvdw/dbus-serialbattery/pull/484
still waiting for approval, but you can try on your own.

**Comment by transistorgit** [comment]
Duplicate of #397
