### ISSUE TITLE
JKBMS V11.26  raspberry venus os large 

### ISSUE THREAD

**Issue by githubfrance** [Louisvdw/dbus-serialbattery#518]
Hi Louis,
Thank you for your work.

**Comment by mr-manuel** [comment]
How did you solve it?

**Comment by githubfrance** [comment]
Hi Louis,

I cut the cable from the JKBMS 485 and kept only the side with the connector to the GPS. I connected the ground, TX and TX to the TTL to USB converter.
It has been running flawlessly for two days now.  

[image.png](https://drive.google.com/file/d/13Cw6J_9btVQWCGmTskhvVRrXPdeD2KXe/view?usp=sharing)

I also tested another TTL converter
 
https://drive.google.com/file/d/1Kadc8Wt0xzEfWW1uRZ9p5hc5X2WTZqsp/view?usp=sharing

https://drive.google.com/file/d/1JOqjtiiXrSSm0qrLVHdL2eSq9X5_-2ce/view?usp=sharing

I will now look for a much smaller TTL converter and see if I can welded directly to the raspberry to keep it into the case.

I will see how to start the serial comm port on Venus OS.

Thank you for your work.
Best regards
Patrick

**Comment by mr-manuel** [comment]
Ok, so related to https://github.com/Louisvdw/dbus-serialbattery/discussions/524. Thanks

**Comment by hahnkarl** [comment]
I dont know if I'm on the right topic but i have issue ( connectet via BLUETOOTH) with 2 of 3 JK devices. one is working well 2 are working also but i only get the voltage of each cell but not the "rest" of datas. the working jk is SW 10.09, the not working SW11.25 maybe you can help me , thanks
