### ISSUE TITLE
serial-starter config should not be called serial-starter.d

### ISSUE THREAD

**Issue by kscholty** [Louisvdw/dbus-serialbattery#520]
**Describe the bug**
The config file for serial-starter is named serial-starter.d.
While this works it prohibits other drivers to put theirr own config there and installation might even fail when anoter config has been installed. the ".d" hints to this being a directory. In fact, the serial-starter will include all files in that directoy ending with ".conf"

**To Reproduce**
Check installation script

**Expected behavior**
The file should be called "dbus-serialbattery.conf" or something similar
and be installed into /data/conf/serial-starter.de

**VenusOS (please complete the following information):**
 - Device type: RaspBerryPi
 - Firmware Version 2.87

**Battery/BMS (please complete the following information):**
n/a

**Additional context**

**Comment by mr-manuel** [comment]
Additional info:
```bash
root@nanopi:~# cat /etc/venus/serial-starter.conf
service cgwacs          dbus-cgwacs
service gps             gps-dbus
service modbus          dbus-modbus-client.serial
service modem           dbus-modem
service mkx             mk2-dbus
service vedirect        vedirect-interface
service fzsonick        dbus-fzsonick-48tl
service imt             dbus-imt-si-rs485tc

alias   rs485           cgwacs:fzsonick:imt:modbus
alias   default         gps:vedirect

include /data/conf/serial-starter.d
```

This is changed with this commit https://github.com/Louisvdw/dbus-serialbattery/pull/468/commits/939324574a1ce49439d79d3d7231f2bcbecb7598 and this PR https://github.com/Louisvdw/dbus-serialbattery/pull/468.
