### ISSUE TITLE
MAX_BATTERY_CHARGE_CURRENT should be retrieved from the system settings

### ISSUE THREAD

**Issue by jdeus** [Louisvdw/dbus-serialbattery#522]
**Is your feature request related to a problem? Please describe.**
MAX_BATTERY_CHARGE_CURRENT is currently a hard setting. However its meaning should be the same as the max charge current defined in VenusOS, and thus its value should be retrieved from the VenusOS's config.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
The setting could eventually be retrieved from the DVCC's settings. But not everyone has DVCC enabled.

**Comment by mr-manuel** [comment]
What for those who have multiple batteries in parallel? How you would handle it, if one battery has a max charge current limit of 40 and the other 60?

What is your application/system to understand your request better?

**Comment by mr-manuel** [comment]
Normally you don‘t set this values. You only enable DVCC that the driver can work with this values.

Many are using Node-RED and [venus-os_dbus-mqtt-battery](https://github.com/mr-manuel/venus-os_dbus-mqtt-battery) to aggregate batteries.

**Comment by jdeus** [comment]
So what's the use case of such config variables exactly ?

**Comment by mr-manuel** [comment]
See [8. DVCC - Distributed Voltage and Current Control](https://www.victronenergy.com/media/pg/Venus_GX/en/dvcc---distributed-voltage-and-current-control.html)
