### ISSUE TITLE
CCL and DCL Maximum 60A??

### ISSUE THREAD

**Issue by Koert1984** [Louisvdw/dbus-serialbattery#534]
hey! Short question. Just got my system up and running but I can't get the CCL and DCL values ​​to change. Remains at 60A No matter what I enter in the config. Do you have a hint for me? I'm running version 0.14.3. The following values ​​are currently included under parameters: CVL = 57.92, CCL = 60.00A (although 150A is set in the config) DCL = 60.00A (although 200A is set in the config)

**Comment by mr-manuel** [comment]
Did you check the [FAQ](https://github.com/Louisvdw/dbus-serialbattery/wiki/FAQ#why-is-the-chargingdischarging-current-limit-ccldcl-smaller-than-the-set-one) in the Wiki?
