### ISSUE TITLE
Current dumping to grid with no solar input after D-bus-serialbattery installation

### ISSUE THREAD

**Issue by josmeijer** [Louisvdw/dbus-serialbattery#589]
**Describe the bug**
After finally (after some bumps) finishing the installation of Dbus SB I found that a sudden Grid feed-in of >4000w was taking place.

I just installed dbus-serial battery drivers and did not change any other parameters.
I allways have AC and DC grid feed in switched on. I was forced to switch them off to avoid a total drain of the battery (I presume)
There are no alarms or messages.
![Screenshot_2023-04-27_14-28-23](https://user-images.githubusercontent.com/35534038/234977947-0e4b94fa-23b6-4fc9-bb2a-d0c1379ae591.png)
![Screenshot_2023-04-27_14-29-47](https://user-images.githubusercontent.com/35534038/234977960-946c1cb3-bfa5-4891-9271-c1310fcafa83.png)

**VenusOS 3.0
 - Device type: Color Control GX
 - Firmware Version 3.0~36

**Battery/BMS 
 - Daly 250A smart BMS
 - Cells: 16 LiFePo 250 Ah
 - Interface: USB-RS485 (factory standard DALY)
 
**Gear
 - EasySolar 48/5000/70 (that is a multiplus 48/5000, MPPT 150/100 and a ColorControlGX )

**Comment by mr-manuel** [comment]
Which devices do you have?

**Comment by josmeijer** [comment]
EasySolar 48/5000/70

**Comment by josmeijer** [comment]
further I have this funny inverted display of discharging since the sun is up and charging when I make my coffee with 3kw draw.

![Screenshot_2023-04-28_01-13-37](https://user-images.githubusercontent.com/35534038/235070633-dd2b4bef-3631-4b33-a540-00bf6868b3be.png)
![Screenshot_2023-04-28_01-20-55](https://user-images.githubusercontent.com/35534038/235070639-366556ea-394b-482a-a36a-7b0c1c9b390e.png)

**Comment by mr-manuel** [comment]
> further I have this funny inverted display of discharging since the sun is up and charging when I make my coffee with 3kw draw.

Please check the FAQ for this.

**Comment by josmeijer** [comment]
While sitting with the coffee I just mentioned I did some thinking:
can it be, that the inverted charge/discharge will as well be the cause of the grid-dumping? 
I don´t know how the algorithm works, but I can imagine this. And if so, you get an avalanche-effect as the more you dump, the more you "charge" .

**Comment by mr-manuel** [comment]
Yes that could be.

[Why is the battery current inverted?](https://louisvdw.github.io/dbus-serialbattery/troubleshoot/faq#why-is-the-battery-current-inverted)

**Comment by josmeijer** [comment]
so "Some Daly BMS send the current as inverted value. This can be correted by setting INVERT_CURRENT_MEASUREMENT to -1"
That sounds easy, as long as you know where to find (-and change) this parameter.
And, I only have SSH acces, as the USB/SD install failed, so changing it in the tar.gz file is no real option.
I do have some experience but that was in the 80's of last century, working CP/M on a Z80 processor. So, though I surprised myself by memorizing quite some of the commands, my knowledge is yet a little rusty, so some direction would be appreciated

**Comment by mr-manuel** [comment]
Take a look at [How to change the default limits](https://louisvdw.github.io/dbus-serialbattery/general/install#how-to-change-the-default-limits) and [How to edit utils.py or config.ini](https://louisvdw.github.io/dbus-serialbattery/general/install#how-to-edit-utilspy-or-configini).

**Comment by josmeijer** [comment]
typical RTFM :-)  
It was all there
And great that all my 80's 
![problemsolved](https://user-images.githubusercontent.com/35534038/235285861-9e2b9e42-f03c-4888-9b12-58fd929b21ad.jpg)
wordstar commands still work in Nano

**Comment by josmeijer** [comment]
![problemsolved](https://user-images.githubusercontent.com/35534038/235286808-58f87f00-227f-4c52-ba86-e0a1ba6e7672.jpg)
typical RTFM case :-)  It was all there.
And great that all my 80's wordstar commands still work in nano.
thnx for guiding me.

**Comment by mr-manuel** [comment]
You’re welcome. I modified also the docs to make them more clear and easy to understand ;-) great that it works now! All problems solved?

**Comment by josmeijer** [comment]
It seems so. 
I was still thinking: can it be that the "some daly BMS's invert charge/discharge" is related to the settings of the inverter protocol (bottom right on the picture)? 

Mine is still set on Victron from an attempt to realise CAN bus communication 


![protocol](https://user-images.githubusercontent.com/35534038/235287874-3dce122f-1b04-49b7-9c57-af7183eac49f.jpg)

**Comment by mr-manuel** [comment]
Please open a discussion for that.
