### ISSUE TITLE
MNB BMS still supported?

### ISSUE THREAD

**Issue by mr-manuel** [Louisvdw/dbus-serialbattery#590]
Is the MNB BMS still supported? It was first disabled and then removed.

* disable MNB battery by default https://github.com/Louisvdw/dbus-serialbattery/commit/65241cbff36feb861ff43dbbcfb2b495f14a01ce

* remove duplicate MNB lines (there were no duplicates?) https://github.com/Louisvdw/dbus-serialbattery/commit/23afec33c2fd87fd4d4c53516f0a25f290643c82

1. Is someone using this BMS with this driver?
2. What are the manual steps to install it?

**Comment by Louisvdw** [comment]
This is still valid. The user needs to install the SPI and another reference that is required before it can be used. So by default it will fail if activated and that is why it is disabled. I'll add a link later to the steps (need to go and search for that post)

**Comment by mr-manuel** [comment]
Ok. Could you add what a user have to do to the [BMS specific install settings](https://louisvdw.github.io/dbus-serialbattery/general/install#bms-specific-settings)?

**Comment by mr-manuel** [comment]
I found only this https://github.com/Louisvdw/dbus-serialbattery/pull/27

**Comment by MikeD2-mnb** [comment]
As this code is specific to one series of chips, at the moment I'm willing to support this on a case by case basis. I do have hardware : Built & tested boards available, or I can make the pcb available for on line purchase, and you can build your own. Code is also subject to revision for python3 language support in Venus os. Note that there are some python libraries that need to be installed on the os manually: the code does NOT do this for you.

**Comment by mr-manuel** [comment]
Since it‘s currently nearly impossible, I will remove it for this time. See [here](https://community.victronenergy.com/comments/231924/view.html).
