### ISSUE TITLE
JKBMS SerailBattery many "Unknown" in parameters

### ISSUE THREAD

**Issue by seamaster101** [Louisvdw/dbus-serialbattery#613]
### Describe the problem

When reviewing the connected JKBMS via SerialBattery 
i noticed the following fields reported as unknown:
1. Switch - Unknown
2. State - Unknown 
3. Relay state - Unknown
4. Alarm State - Unknown
Under Diagnostics (it is listed actually twice with different sub-menus)
     Alarm -Unknown
     Main Switch - Unknown
     Heater  - Unknown
     Internal Fan - Unknown 
I understand that some of this is because data is not provided by the BMS but i care the most about the Alarm State
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7897023/236598995-25f6422e-d003-4e4f-beeb-e6a3842497e0.png">

I presume the alarm state should be known as under Alarms we have OK for everything, 
<img width="650" alt="image" src="https://user-images.githubusercontent.com/7897023/236599014-184037e5-03ff-4850-8d3a-de5505658aa7.png">

so AlarmState should be "OK"
<img width="630" alt="image" src="https://user-images.githubusercontent.com/7897023/236598966-89fadd11-ae80-4470-9ea8-993f7c3e912c.png">

Also there is a lot of parameters that look out of place like "air temperature", "Starter Voltage" etc. Can some one please elaborate on these? 
<img width="480" alt="image" src="https://user-images.githubusercontent.com/7897023/236599315-1acc32c5-719e-46d2-b0a5-aaa7b9884781.png">

### Driver version

0.14.3

### Venus OS device type

Raspberry Pi

### Venus OS version

v3.0

### BMS type

JKBMS / Heltec BMS

### Cell count

4Cell multiple batteries

### Connection type

Serial USB adapter to RS485

### Config file

```ini
original
```

### Relevant log output

```shell
can provide what is needed
```

**Comment by mr-manuel** [comment]
Thats already fixed in the next version. You can try the nightly to solve hat.

**Comment by seamaster101** [comment]
@mr-manuel i did update to this version:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/7897023/236731493-4c482170-39bc-45f0-ad10-d70046364207.png">
still looses the name after reboot

**Comment by mr-manuel** [comment]
See https://github.com/Louisvdw/dbus-serialbattery/issues/100
