### ISSUE TITLE
Wiki Link Broken

### ISSUE THREAD

**Issue by nighteagle1974** [Louisvdw/dbus-serialbattery#634]
### Describe the problem

Here i read the new Wiki and the Link for the explaining of the Setting config.ini is missing

**Driver version >= v1.0.0
Copy the values from /data/etc/dbus-serialbattery/config.default.ini to /data/etc/dbus-serialbattery/config.ini you want to change. All options can also be copied from [here]**

Site does not exists: (https://github.com/Louisvdw/dbus-serialbattery/blob/jkbms_ble/etc/dbus-serialbattery/config.default.ini).

### Driver version

Wiki

### Venus OS device type

Cerbo GX

### Venus OS version

v2.92

### BMS type

Daly Smart BMS

### Cell count

8s

### Connection type

Serial USB adapter to RS485

### Config file

```ini
Wiki Link Broken
```

### Relevant log output

```shell
Wiki Link Broken
```

**Comment by mr-manuel** [comment]
Thanks, I fixed it!
