### ISSUE TITLE
Charge Voltage Limitation linear switch back on SOC

### ISSUE THREAD

**Issue by wetty** [Louisvdw/dbus-serialbattery#635]
### Is your feature request related to a problem? Please describe.

My 18 Cells are perfectly balanced that the voltage difference stays always under 0.01 V. (most often 0.001-0.007)
I use the linear CVL and the charging voltage is correctly changed to float voltage after they reached max voltage.
They stay in float voltage and dont switch back to max voltage as CELL_VOLTAGE_DIFF_TO_RESET_VOLTAGE_LIMIT is never reached.
 

### Describe the solution you'd like

I would like to have the solution that in linear mode the switch back to max voltage also happens when the SOC_LEVEL_TO_RESET_VOLTAGE_LIMIT is reached

### Additional context

I use the Version 1.0.0-jkbms_ble (20230505)

**Comment by mr-manuel** [comment]
Makes sense. It will be included in the next pre-release and release.
