### ISSUE TITLE
BMS SOC vs. Multiplus SOC

### ISSUE THREAD

**Issue by kr0815** [Louisvdw/dbus-serialbattery#640]
### Describe the problem

In the VRM-Portal, i see the SOC provided by dbus-serialbattery and the one provided by the internal meassurement

If i change the BMS SOC, the Mutiplus SOC will also be changed?

Is this behaviour wanted?

### Driver version

1.0.0 installed with nightly built

### Venus OS device type

Raspberry Pi

### Venus OS version

3.00 36

### BMS type

Daly Smart BMS

### Cell count

16

### Connection type

Serial USB adapter to TTL

### Config file

```ini
*
```

### Relevant log output

```shell
*
```

**Comment by mr-manuel** [comment]
> If i change the BMS SOC, the Mutiplus SOC will also be changed?

Is this a statement or a question?

From what I know, the SoC of the battery monitor selected should be displayed. Where exactly in the VRM portal do you mean? Please post a screenshot.

**Comment by kr0815** [comment]
In VRM, i see the Values of the Daly BMS - read out by serialbattery, and, theoretically, the value calculated by the shunt in the Multiplus

But it looks like serialbattery is also overwriting the internal Multiplus value?

![Zwischenablage01](https://github.com/Louisvdw/dbus-serialbattery/assets/16240382/17d02efb-8822-4c15-a37c-db5021c67fbe)

**Comment by mr-manuel** [comment]
In the remote console/GUI go to Settings -> System setup -> Battery measurements and enable the devices you want to see in VRM.

**Comment by kr0815** [comment]
I have them both enabled 

Problem is, that internal Value is always the same as the one from serialbattery

I think there is a bug that serialbattery overwrites also the internal calculated SOC?

**Comment by mr-manuel** [comment]
No, the driver is not overwriting nothing. Probably it‘s some calculation in [`dbus-systemcalc-py`](https://github.com/victronenergy/dbus-systemcalc-py).

Please open a question in the Victron Community.

**Comment by kr0815** [comment]
Thanks, i´ll try that
Really strange behaviour, as vor Voltage and Current, i get different Valus, but SOC is always the same

**Comment by mr-manuel** [comment]
Please link your post here, so other users with the same problem can follow that
