### ISSUE TITLE
Daly BMS reporting charging when discharging and Amps have inverted sign

### ISSUE THREAD

**Issue by ddarek2000** [Louisvdw/dbus-serialbattery#65]
Daly Smart BMS 150A 16S has a firmware problem that reports inverted sign for Amps.  This results in BMS reporting charging when inverter is running , and BMS discharing when the charger is running.  

I would like to have a variable / switch that would cause the values to invert when such a problem is detected by the user.  This should be manual configuration , not an automatic switch.

I am considering replacing the BMS.

BMS is connected using UART to USB connection which works perfectly.  Above scenario is also observed using Bluetooth IOS app and PC app
![Daly_Smart_BMS](https://user-images.githubusercontent.com/40216289/139064054-c5633ce9-ab7b-46a6-add2-c3bac5e3e69c.png)
.

**Comment by Louisvdw** [comment]
In the next release you can change the utils.py to invert the current measurement
`INVERT_CURRENT_MEASUREMENT = -1`
