### ISSUE TITLE
Jkbms via BLe not used as battery 

### ISSUE THREAD

**Issue by k2dp2k** [Louisvdw/dbus-serialbattery#669]
### Describe the problem

Hey hoo 🙋🏻‍♂️

My JKbms is recognised by venusos inside the menu but it is not acting and showing as a connected battery… Any ideas about that ?

regards,
Daniel

### Driver version

1.0.0

### Venus OS device type

Raspberry Pi

### Venus OS version

3.0

### BMS type

JKBMS / Heltec BMS

### Cell count

8

### Connection type

Bluetooth

### Config file

```ini
Standart
```

### Relevant log output

```shell
I have none
```

**Comment by mr-manuel** [comment]
Please provide more informations. Like the exact driver and Venus OS version. It has a reason why we need this.

Do also provide some screenshots of what exactly do you mean. Where is it not showing as connected battery?

**Comment by k2dp2k** [comment]
I will close this case, it was an issue with the unique identifier. I'm using an rpi3 a+ and missed to make the changes in the "/sbin/get-unique-id" file... now everything is working fine 👌
