### ISSUE TITLE
REC BMS integration

### ISSUE THREAD

**Issue by Louisvdw** [Louisvdw/dbus-serialbattery#7]
Add the REC BMS basic communication to the driver.

- [ ] SOC
- [ ] Battery voltage
- [ ] Charge/discharge current
- [ ] Temprature
- [ ] Min/max cell voltages
- [ ] protection notifications

[Uploading UserManual_REC_Victron_BMS.pdf…]()

**Comment by mpvader** [comment]
Hi @Louisvdw , what would be the benefit of this? REC is already supported via CAN-bus. More options, is often more questions, more work, more confusion, and so forth

**Comment by Louisvdw** [comment]
Hi @mpvader, that is good feedback. I had a request from a user. Did not know that it is already supported via CAN-bus.
Then I can close this ticket
