### ISSUE TITLE
reverse reading charging / discharging on Daly BMS

### ISSUE THREAD

**Issue by nhybrow** [Louisvdw/dbus-serialbattery#70]
Hello,
On the Daly bms, when the battery is charging, the BMS displays discharging, and when the battery is discharging it displays charging. On venusOS and VRM the direction of the current is therefore reversed, the reading of information is therefore mistaken. Is there a way to reverse the direction in order to interpret the values as they are displayed on the BMV, so that the current direction is correct?
Thanks in advance,

**Comment by nhybrow** [comment]
![Screenshot_2021-11-09-08-10-53-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/9859948/140878487-f61fe42b-689b-41ea-9aa2-bc79cd9f9812.jpg)

**Comment by Louisvdw** [comment]
Hi @nhybrow 
There is already an solution for this that will be included in the next release.
See issue #65
