### ISSUE TITLE
Using JKBMS name the is advertised in place of SerialBattery(JKBMS_BLE).

### ISSUE THREAD

**Issue by githubfrance** [Louisvdw/dbus-serialbattery#717]
### Is your feature request related to a problem? Please describe.

Hi
With the JKBMS app we can change the name of the BMS
This name is advertised as you can see with bluetoothctl scan on
(my BMS's)
Device C8:47:8C:EC:F8:F9 JKBMS-Display
Device C8:47:8C:ED:06:11 JKBMS-Heating

But you are not using this name, you replace it with SerialBattery(JKBMS_BLE).

### Describe the solution you'd like

I would like to have the advertised name used in Device/Name on Venus OS

### Describe alternatives you've considered

An alternative coud be using the name in config.ini

BLUETOOTH_BMS = JKBMS-Heating C8:47:8C:ED:06:11, JKBMS-Display C8:47:8C:EC:F8:F9

**Comment by mr-manuel** [comment]
Can you send a screenshot of the JKBMS where you entered the name?

Please post a screenshot of all values on the `Device` in the remote console/GUI -> SerialBattery -> Device.

**Comment by mr-manuel** [comment]
BTW, the name can already be set in the config.ini or by changing it in the remote console/GUI -> SerialBattery -> Device -> Name

**Comment by githubfrance** [comment]
regarding config.ini how can I add the name for each mac address ?

**Comment by mr-manuel** [comment]
It's still in the alpha test phase, so there is no documentation yet except the config default file: https://github.com/Louisvdw/dbus-serialbattery/blob/4af10dd9d323ee9e88c82d8cec3b69a9d04fddfe/etc/dbus-serialbattery/config.default.ini#L197-L201

Please enter the name via GUI and the entry will be added automatically to the config file. I don't know how it behaves for the Bluetooth connected devices, but it's planned to link the name to the `unique identifier`, so that if the port changes the name get not lost. See https://github.com/Louisvdw/dbus-serialbattery/issues/100#issuecomment-1585743408.

**Comment by ogurevich** [comment]
In the JKBMS app it looks like this:
![IMG_1848](https://github.com/Louisvdw/dbus-serialbattery/assets/50322596/352e1e37-9c0e-414f-ab30-edf22c63aacf)
the name can be adjusted by user
![IMG_1849](https://github.com/Louisvdw/dbus-serialbattery/assets/50322596/107fca32-8b36-4251-82cc-a6e45859ee97)
![IMG_1850](https://github.com/Louisvdw/dbus-serialbattery/assets/50322596/222ba0c1-fa4c-4de7-b9b7-4e315d7817e4)
On DBUS we can access this value under:
com.victronenergy.battery.ttyUSB1 and com.victronenergy.battery.ttyUSB2

![Screenshot 2023-06-18 at 21 28 23](https://github.com/Louisvdw/dbus-serialbattery/assets/50322596/ae1a04f5-f573-4483-b19b-06e0f1f6e8a3)
 After the reboot  of cerbo gx or reinserting USBs the port assignment may change

**Comment by mr-manuel** [comment]
> On DBUS we can access this value under:
> com.victronenergy.battery.ttyUSB1 and com.victronenergy.battery.ttyUSB2

Ok, when I was testing this, I got another field. If you open a BMS in the app and scroll down to the limits there is also a `User Private Data` field or something like that. What is in this field in your case?


> After the reboot of cerbo gx or reinserting USBs the port assignment may change

We are working on it in https://github.com/Louisvdw/dbus-serialbattery/issues/718

**Comment by ogurevich** [comment]
ups, written in wrong topic: https://github.com/Louisvdw/dbus-serialbattery/issues/718#issuecomment-1596268819
