### ISSUE TITLE
Is there a way to use serialbattery just for monitoring without any controlling tasks?

### ISSUE THREAD

**Issue by Philipp92** [Louisvdw/dbus-serialbattery#740]
### Describe the problem

I installed serialbattery just to check the individuall cell voltages via VRM-Portal from holidays.
Since the installation my system isnt working like before. I think it is because of some limits and controlling from serialbattery.

Is there an option to disable all these limits and controlling?
I just want a monitor.

Thank you!

### Driver version

-

### Venus OS device type

Cerbo GX

### Venus OS version

-

### BMS type

JKBMS / Heltec BMS

### Cell count

16

### Connection type

Serial USB adapter to TTL

### Config file

```ini
-
```

### Relevant log output

```shell
-
```

**Comment by mr-manuel** [comment]
Please check the FAQ.
