### ISSUE TITLE
Mistake in the FAQ?

### ISSUE THREAD

**Issue by Tingeltangelbobi** [Louisvdw/dbus-serialbattery#788]
### Describe the bug

At the point:
Why is the charging/discharging current limit (CCL/DCL) smaller than the set one?
-> Driver version >= v1.0.0
It says:
The limits are based on percentages of MAX_CHARGE_CURRENT_CV and MAX_DISCHARGE_CURRENT_CV values,

Shouldn't it say?:
The limits are based on percentages of **MAX_BATTERY_CHARGE_CURRENT** and **MAX_BATTERY_DISCHARGE_CURRENT** values.

### How to reproduce

1. Go to FAQ
2. Click on FAQ
3. Scroll down to Why is the charging/discharging current limit (CCL/DCL) smaller than the set one?
-> Driver version >= v1.0.0

### Expected behavior

Shouldn't it say?:
The limits are based on percentages of **MAX_BATTERY_CHARGE_CURRENT** and **MAX_BATTERY_DISCHARGE_CURRENT** values.

### Driver version

1.0.0

### Venus OS device type

Please select

### Venus OS version

3

### BMS type

Daly Smart BMS

### Cell count

16

### Connection type

Serial USB adapter to TTL

### Config file

```ini
no confic problem
```

### Relevant log output

```shell
no log
```

**Comment by mr-manuel** [comment]
Thank you. I fixed it with https://github.com/Louisvdw/dbus-serialbattery/commit/d89fb9a8ddb39e08391c534f8ccab3950e487caf
