### ISSUE TITLE
Error in the file /data/log/serial-starter/current

### ISSUE THREAD

**Issue by HermanLik** [Louisvdw/dbus-serialbattery#84]
**Describe the bug**
@4000000061d721bc1b35b89c *** starting serial-starter ***
@4000000061d721bd0653fccc find: /service/dbus-serialbattery/service/service/service/.../service/: **Too many levels of symbolic links**

**To Reproduce**
1. Install v0.10 release 
2. Connect FT232R to USB port, restart Raspberry Pi 
3. Open file /data/log/serial-starter/current

**Expected behavior**
There should not be an endless nesting of service folders

**Screenshots**
see above "Describe the bug"

**VenusOS (please complete the following information):**
 - Device type: Raspberry Pi 4
 - Firmware Version: Venus OS v2.80_33-large-24

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: It doesn't matter at this step.
 - Cells: -
 - Interface: USB-RS485

**Additional context**
-

**Comment by Louisvdw** [comment]
There is a new [beta4 release](https://github.com/Louisvdw/dbus-serialbattery/releases/tag/v0.11beta4) that should solve this issue. Please give it a test
