### ISSUE TITLE
Temperature sensors reversed Overkill BMS

### ISSUE THREAD

**Issue by lfhoward** [Louisvdw/dbus-serialbattery#847]
### Describe the bug

Last night the temperature dropped low enough for my battery heater to kick on this morning. My battery heater is programmed to turn on at 39 degrees F and turn off at 45 degrees F between 0600 and 1400. The outdoor temperature last night went down below 30 degrees F, with the battery itself coming down to 37 degrees F before the battery heater came on at 6 AM. 

I have a BMV Victron battery monitor with a wired temperature sensor attached to one of the battery posts. This is the sensor used to turn the battery heater on and off via the BMV relay. The Overkill BMS has 2 of its own temperature sensors, one located in the circuit board (MOSFET temperature) and another on a wire that is embedded between my battery cells (Battery Temperature). 

These two BMS temperature sensors seem to be revered in the Remote Console and VRM. See the following screen captures.

BMV battery temperature showing 45 degrees F after heating the battery this morning
![temp-Imaget-G68-Ez](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/3f4f54c3-6418-43d9-a07c-4ab20357e8ac)

Overkill BMS sensors reporting 35 degrees F for battery and 46 degrees F for MOSFET temperatures. These are backwards.
![temp-Imager-AFl-Pj](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/97b9be0a-cb05-4994-8ec5-dc829f101874)

The air temperature environment around the battery was 26 degrees F (RuuviTag).
![temp-Image-Zvh-XTh](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/4dbe8c6c-211c-4647-afc3-9306b81f8b70)

Remote console view showing temperatures.
![temp-Imaged9-Csz8](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/3a6ca90f-0121-4e89-b60f-482e6b0c76e4)

VRM view showing temperature history.
![temp-Image1-V0bp-O](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/5513674b-5f00-4307-963e-8f04f6a232d3)

Thanks for your help!

### How to reproduce

Change the battery temperature quickly and compare to a second battery temperature sensor.

### Expected behavior

The BMS battery temperature reading should mirror the BMV battery temperature sensor. The MOSFET sensor should read closer to the external air temperature sensor.

### Driver version

1.0.20230902dev

### Venus OS device type

Raspberry Pi

### Venus OS version

v 3.12

### BMS type

Smart BMS (LLT, JBD, Overkill Solar)

### Cell count

4

### Connection type

Serial USB adapter to TTL

### Config file

```ini
see screen shots above
```

### Relevant log output

```shell
see screen shots above
```

**Comment by mr-manuel** [comment]
Hi, please don't post links to external images, but insert the images directly on GitHub. Else in some weeks/months the images are not available anymore.

Unfortunately I do not understand what exactly the problem is or what you expect. The driver can only read the data the BMS is providing.

**Comment by lfhoward** [comment]
I thought about what you said, “The driver can only read the data the BMS is providing,” and figured the names for the 2 BMS temperature sensors had to be able to be set somewhere. I came up with two options. 

One is inside the xiaoxiang BMS app, where “Temp. Sensor 1” and “Temp. Sensor 2” can be renamed. This should fix it at the BMS level. The temperature sensors can be renamed on the front page, by clicking the edit button next to each sensor name. 

The second option is inside the config.default.ini file associated with dbus-serialbattery. (See https://github.com/Louisvdw/dbus-serialbattery/blob/master/etc/dbus-serialbattery/config.default.ini) In that config file there is a way to name the battery temperature sensors as well as choose which sensor(s) to report as the battery temperature. Battery temperature settings begin at line 208 and go through line 227.

I will try both this weekend and report back what works. Meanwhile, thanks for the info about where the battery names come from. That was what got me pointed in the right direction.

**Comment by mr-manuel** [comment]
Any news on this?

**Comment by lfhoward** [comment]
Just an update - sorry it took me so long to test this out.

1. Changing the names of the temperature sensors inside the JBD bms does not change their names on the VRM side. 

2. Choosing a specific temperature sensor to report in config.ini - did not work as expected. The first battery sensor on the BMS is always reported as "Battery" even though it is actually the temp sensor inside the BMS itself, and the second temperature sensor is always reported as MOSFET even though is actually the remote battery sensor inside the cells. Naming them in the settings has no effect on the GUI. Setting Temp 2 as the primary makes the BMS temp on the GUI disappear.
