### ISSUE TITLE
Automatic calculation of the voltage drop by specifying the cable resistance

### ISSUE THREAD

**Issue by mlapp** [Louisvdw/dbus-serialbattery#854]
### Is your feature request related to a problem? Please describe.

In the current dev a voltage drop is introduced. This is shown as a fixed increase/decrease on the voltage measured by the BMS. But that is not enough because the voltage drop also depends on the resistance of the cable and the current flowing through the cable.

### Describe the solution you'd like

A further parameter “cable resistance” is introduced.
This can then be used to calculate the current-induced voltage drop on the cable and add it to the BMS voltage.
Even if the resistance of the cable is in the milliohm range, this resistance is clearly noticeable, especially with large currents.

**Comment by mr-manuel** [comment]
I think that only a small part of the users will set this right. Therefore I‘m not for this change.
