### ISSUE TITLE
DALY BMS: Reading Alarms and used Ah 

### ISSUE THREAD

**Issue by Thomk-63** [Louisvdw/dbus-serialbattery#86]
**Is your feature request related to a problem? Please describe.**
The current driver is already really good! hank you for this and all the effort!
But there are 4 things missing:
1. Alarms/Errors of the DALY
2. Display of used Ah (possibly there is not such a value with the DALY?!)
3. Display of activated balancer
4. Display of installed capacity

![Bildschirmfoto 2022-01-30 um 18 30 23](https://user-images.githubusercontent.com/98706925/151711710-397bd995-cceb-4ad2-9c0a-ce5f3695128a.png)
![Bildschirmfoto 2022-01-30 um 18 31 44](https://user-images.githubusercontent.com/98706925/151711719-59e2cb92-c0d4-4367-ba4d-72caf8d8a459.png)
![Bildschirmfoto 2022-01-30 um 18 31 01](https://user-images.githubusercontent.com/98706925/151711760-fb7cd26b-92b6-44c8-be32-e01a2f0ad4c5.png)

**Describe the solution you'd like**
Display of the Alarms/Errors and the values

**Additional context**
DALY 4S 12V 100A model R05A
Raspberry Pi
V2.73

**Comment by Louisvdw** [comment]
Pull request #90 now add support for alarms on Daly BMS

**Comment by CaptKrisp** [comment]
@Thomk-63 The Daly docs do not specify how to pull configured capacity.
The current code now includes a BATTERY_CAPACITY variable in utils.py to specify your battery capacity.
Most Alarm data is now pulled from BMS.

**Comment by Thomk-63** [comment]
Hi Louis,
which files need to be updated? all?

Regards,
Thomas
Thomas + Nicole Krüger
***@***.***

**Comment by Thomk-63** [comment]
Thanks, I will do and will report.

Regards,
Thomas
Thomas + Nicole Krüger
***@***.***

**Comment by Thomk-63** [comment]
Hi Louis,

in the meantime I could test a little.
In general the software still works after your modifications. The capacity value of the battery can be seen in the Venus console.
But when I provoked a cell voltage high alarm (cell volt high level 2), no alarm was reported in the Venus console.

Here two screenshots at the same time of the alarm:



Regards,
Thomas

Thomas + Nicole Krüger
***@***.***

**Comment by Louisvdw** [comment]
This is included in the new release v0.12
Note the cell voltages is disabled for now as it was giving issues
