### ISSUE TITLE
Driver does not start anymore after editing config.default.ini

### ISSUE THREAD

**Issue by bastawine** [Louisvdw/dbus-serialbattery#885]
### Describe the bug

hi , im new 

Gerbo GX

after install once enter : nano /data/etc/dbus-serialbattery/config.default.ini 
it works but second time only half the info is there ? 
  
  also when i add any thing : nano /data/etc/dbus-serialbattery/config.ini 
  
  after reboot driver doesnt work any more ? 
  
  also i can only add one name for 1 daly bms ( 1 of 3 ) 
  
CUSTOM_BATTERY_NAMES = /dev/ttyACM0:DalyBMS1
CUSTOM_BATTERY_NAMES = /dev/ttyACM1:DalyBMS3
CUSTOM_BATTERY_NAMES = /dev/ttyACM2:DalyBMS2 

if add to : nano /data/etc/dbus-serialbattery/config.ini  ( after reboot driver stops working ) 

### How to reproduce

after install once enter : nano /data/etc/dbus-serialbattery/config.default.ini 
it works but second time only half the info is there ? 
  
  also when i add any thing : nano /data/etc/dbus-serialbattery/config.ini 
  
  after reboot driver doesnt work any more ? 
  
  also i can only add one name for 1 daly bms ( 1 of 3 ) 
  
CUSTOM_BATTERY_NAMES = /dev/ttyACM0:DalyBMS1
CUSTOM_BATTERY_NAMES = /dev/ttyACM1:DalyBMS3
CUSTOM_BATTERY_NAMES = /dev/ttyACM2:DalyBMS2 

if add to : nano /data/etc/dbus-serialbattery/config.ini  ( after reboot driver stops working ) 

### Expected behavior

after install once enter : nano /data/etc/dbus-serialbattery/config.default.ini 
it works but second time only half the info is there ? 
  
  also when i add any thing : nano /data/etc/dbus-serialbattery/config.ini 
  
  after reboot driver doesnt work any more ? 
  
  also i can only add one name for 1 daly bms ( 1 of 3 ) 
  
CUSTOM_BATTERY_NAMES = /dev/ttyACM0:DalyBMS1
CUSTOM_BATTERY_NAMES = /dev/ttyACM1:DalyBMS3
CUSTOM_BATTERY_NAMES = /dev/ttyACM2:DalyBMS2 

if add to : nano /data/etc/dbus-serialbattery/config.ini  ( after reboot driver stops working ) 

### Driver version

latest master

### Venus OS device type

Cerbo GX

### Venus OS version

3.12

### BMS type

Daly Smart BMS

### Cell count

16s

### Connection type

Serial USB adapter to RS485

### Config file

```ini
[DEFAULT]

; If you want to add custom values/settings, then check the values/settings you want to change in "config.default.ini"
; and insert them below to persist future driver updates.

; Example (remove the semicolon ";" to uncomment and activate the value/setting):
; MAX_BATTERY_CHARGE_CURRENT = 50.0
; MAX_BATTERY_DISCHARGE_CURRENT = 60.0


CUSTOM_BATTERY_NAMES = /dev/ttyACM0:SerialBattery(Daly)
```

### Relevant log output

```shell
?
```

### Any other information that may be helpful

incomplete ??
( /data/etc/dbus-serialbattery/config.default.ini  )

```ini
[DEFAULT]

; --------- Set logging level ---------
; ERROR: Only errors are logged
; WARNING: Errors and warnings are logged
; INFO: Errors, warnings and info messages are logged
; DEBUG: Errors, warnings, info and debug messages are logged
LOGGING = INFO

; --------- Battery Current limits ---------
MAX_BATTERY_CHARGE_CURRENT    = 100.0
MAX_BATTERY_DISCHARGE_CURRENT = 100.0

; --------- Cell Voltages ---------
; Description: Cell min/max voltages which are used to calculate the min/max battery voltage
; Example: 16 cells * 3.45V/cell = 55.2V max charge voltage. 16 cells * 2.90V = 46.4V min discharge voltage
MIN_CELL_VOLTAGE   = 2.900
; Max voltage (can seen as absorption voltage)
MAX_CELL_VOLTAGE   = 3.450
; Float voltage (can be seen as resting voltage)
FLOAT_CELL_VOLTAGE = 3.375

; --------- SOC reset voltage ---------
; Description: May be needed to reset the SoC to 100% once in a while for some BMS, because of SoC drift.
;              Specify the cell voltage where the SoC should be reset to 100% by the BMS.
;                - JKBMS: SoC is reset to 100% if one cell reaches OVP (over voltage protection) voltage
;              As you have to adopt this value to your system, I reccomend to start with
;              OVP voltage - 0.030 (see Example).
;                - Try to increase (add) by 0.005 in steps, if the system does not switch to float mode, even if
;                  the target voltage SOC_RESET_VOLTAGE * CELL_COUNT is reached.
;                - Try to decrease (lower) by 0.005 in steps, if the system hits the OVP too fast, before all
;                  cells could be balanced and the system goes into protection mode multiple times.
; Example: If OVP is 3.650, then start with 3.620 and increase/decrease by 0.005
; Note: The value has to be higher as the MAX_CELL_VOLTAGE
SOC_RESET_VOLTAGE  = 3.650
; Specify after how many days the soc reset voltage should be reached again
; The timer is reset when the soc reset voltage is reached
; Leave empty if you don't want to use this
; Example: Value is set to 15
; day 1: soc reset reached once
; day 16: soc reset reached twice
; day 31: soc reset not reached since it's very cloudy
; day 34: soc reset reached since the sun came out
; day 49: soc reset reached again, since last time it took 3 days to reach soc reset voltage
SOC_RESET_AFTER_DAYS =

; --------- Bluetooth BMS ---------
; Description: Specify the Bluetooth BMS and it's MAC address that you want to install. Leave emty to disable
; -- Available Bluetooth BMS:
; Jkbms_Ble, LltJbd_Ble
; Example for one BMS:
; BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:00:00:00
; Example for multiple BMS:
; BLUETOOTH_BMS = Jkbms_Ble C8:47:8C:00:00:00, Jkbms_Ble C8:47:8C:00:00:11, Jkbms_Ble C8:47:8C:00:00:22
BLUETOOTH_BMS =

; --------- CAN BMS ---------
; Description: Specify the CAN port(s) where the BMS is connected to. Leave empty to disable
; -- Available CAN BMS:
; Daly_Can, Jkbms_Can
; Example for one CAN port:
; CAN_PORT = can0
; Example for multiple CAN ports:
; CAN_PORT = can0, can8, can9
CAN_PORT =

; --------- BMS disconnect behaviour ---------
; Description: Block charge and discharge when the communication to the BMS is lost. If you are removing the
;              BMS on purpose, then you have to restart the driver/system to reset the block.
; False: Charge and discharge is not blocked on BMS communication loss
; True: Charge and discharge is blocked on BMS communication loss, it's unblocked when connection is established
;       again or the driver/system is restarted
BLOCK_ON_DISCONNECT = False

; --------- Charge mode ---------
; Choose the mode for voltage / current limitations (True / False)
; False is a step mode: This is the default with limitations on hard boundary steps
; True is a linear mode:
;     For CCL and DCL the values between the steps are calculated for smoother values (by WaldemarFech)
;     For CVL max battery voltage is calculated dynamically in order that the max cell voltage is not exceeded
LINEAR_LIMITATION_ENABLE = True

; Specify in seconds how often the linear values should be recalculated
LINEAR_RECALCULATION_EVERY = 60
; Specify in percent when the linear values should be recalculated immediately
; Example: 5 for a immediate change, when the value changes by more than 5%
LINEAR_RECALCULATION_ON_PERC_CHANGE = 5


                                                                                                                                                     [ Read 332 lines ]
^G Get Help       ^O Write Out      ^W Where Is       ^K Cut Text       ^J Justify        ^C Cur Pos        M-U Undo          M-A Mark Text     M-] To Bracket    M-Q Previous      ^B Back           ^◀ Prev Word      ^A Home           ^P Prev Line      M-▲ Scroll Up     ^▲ Prev Block     M-( Beg of Par
^X Exit           ^R Read File      ^\ Replace        ^U Paste Text     ^T To Spell       ^_ Go To Line     M-E 
```

**Comment by mr-manuel** [comment]
![grafik](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/d41a8352-81c6-49f8-9b40-8382f5912619)

![grafik](https://github.com/Louisvdw/dbus-serialbattery/assets/12592765/961721c1-77e2-469a-88f9-dac2db15e030)

**Comment by bastawine** [comment]
hi , sorry for the late response 

i found out that i did something wrong indeed , problem is fixed ( naming the batteries i did wrong ) 

but now i found out that, using  firmware : 1.0.20231117 dev

when i use battery aggregator 2.4  ( pulguero )  with 3 batteries ( daly bms ) soon 4 ;) 

the gerbo GX restarts randomly  ( about 10 times a day ) already going to place 100uf 100V condensator to be sure 

but today i changed the battery monitor in systemsetup to multiplusII , and it seems to fix this rebooting problem , but ofc i want to use the aggregated serrial drivers ( the controlling bms in dvcc still is aggregator ) 

its caused due high cpu load i monitored it for a while via vrm -> dbus round trip time and every time it reboots its at wel obove 100ms ( 852ms some times ) but those are peaks  most of it is around 10-30 ms 

and it mostly happends when discharging the batterys

thes are my settings : 

( nano /data/etc/dbus-serialbattery/config.ini )

MAX_BATTERY_CHARGE_CURRENT = 75.0
MAX_BATTERY_DISCHARGE_CURRENT = 100.0
CUSTOM_BATTERY_NAMES = /dev/ttyACM0:DalyBMS1,/dev/ttyACM1:DalyBMS3,/dev/ttyACM2:DalyBMS2  	
INVERT_CURRENT_MEASUREMENT = -1   								
SOC_LOW_WARNING = 0
SOC_LOW_ALARM = 0
BMS_TYPE = Daly

im going to do some test today , maybe going back to driver : 1.0.20231116 ?

**Comment by mr-manuel** [comment]
Check the CPU usage with htop. See https://github.com/Louisvdw/dbus-serialbattery/issues/808#issuecomment-1723817057

**Comment by bastawine** [comment]
![Schermafbeelding 2023-12-18 141634](https://github.com/Louisvdw/dbus-serialbattery/assets/152805357/3b94d0ff-2a42-4df4-ab5e-8c8a3528623b)

**Comment by bastawine** [comment]
![Schermafbeelding 2023-12-18 142629](https://github.com/Louisvdw/dbus-serialbattery/assets/152805357/210953e1-08f3-4d20-affe-0365d5c966b2)


after about 10 mins log

**Comment by bastawine** [comment]
<img width="1917" alt="image" src="https://github.com/Louisvdw/dbus-serialbattery/assets/152805357/8c9d6e3a-1749-4ead-9fa5-811509686794">

this is when i set : system setup -> monitor back to aggregator  ( and ess optimized withouit battery life )

**Comment by bastawine** [comment]
node red and signalK are disabled 

it seems to increase cpu load, when ess set to optimized with no battery life

 with battery life the load drops  ...

same goes when i set to keep batterys charge cpu load increase

**Comment by mr-manuel** [comment]
Maybe the latest Venus OS Beta can help you. There a new MQTT Broker was implemented that has a much lower CPU usage.

**Comment by bastawine** [comment]
i was thinking to do factory reset on the gerbo gx and instal from defaults , something must be wroing with these cpu loads ?

**Comment by DirkReudenbach** [comment]
I have (had) similar issues with the cpu load.In my case it is happening with Nodered on Cerbo large version and the serial driver. Both working alone fine but not together. I did a factory reset on the Cerbo as well and it is not rebooting so often but still a very high cpu load

**Comment by bastawine** [comment]
first i try , the latest venus os beta 

after that i will try factory reset  , but its insane such expensive equipment has this kind of problems 

and is it better to install serial driver non beta ? ( or cant i give names to batteries then ? )

and is it with everyone using this setup or is it a specific batch of gerbo gx ?

**Comment by bastawine** [comment]
i already did find out that in a single phase configuration like mine 

setting the  ess singephase regulation to single helped lower cpu load about 10%

**Comment by DirkReudenbach** [comment]
in my case it happens with all drivers of serial driver and Cerbo gx and i tried severals. I'm running a 3ph ESS

**Comment by bastawine** [comment]
so in worse case i need to go via RaspberryPi device ....

**Comment by bastawine** [comment]
i just installed latest beta small on gerbogx , and it did drop some cpu load now , but still 80-99 % ...  ;(

but i saw in your case the reset to default did help ?

**Comment by DirkReudenbach** [comment]
in my case it helped a bit but still in that range what you described. With small (without Nodered my cpu load is much less. If you have still such a high cpu load with the small image you should give it a try to setup the Cerbo to default

**Comment by mr-manuel** [comment]
You could also try to optimize your Node-RED configuration. In the Victron Nodes there is now an option to trigger only, if the value has changed instead of every few seconds.

**Comment by bastawine** [comment]
yes but the thing i installed small pakkge beta , without node red now , and still that high 

but it worked this night an morning witout reboots , i do see the monitor reacts very slow also the animations on the display are slow ..

**Comment by bastawine** [comment]
i also disabled the wifi acces point and bms can 

and that dropped cpu load 20% at least
