### ISSUE TITLE
Victron ESS work discharge when grid connected to loads

### ISSUE THREAD

**Issue by RobDuthie** [Louisvdw/dbus-serialbattery#886]
### Describe the problem

What are the full set of settings for the Victron with grid connection and ESS  is activated.
DVCC tuned on
Under the battery settings the IO is showing all off?
As the battery wont discharge to the loads when connected to the grid, but works OK off grid?
Battery type is a EG4
EG4® LiFePower4 | 24V 200AH Lithium Iron Phosphate Battery

### Driver version

latest ver

### Venus OS device type

Raspberry Pi

### Venus OS version

release V3.13

### BMS type

Smart BMS (LLT, JBD, Overkill Solar)

### Cell count

?

### Connection type

Raspberry Pi RS485 HAT

### Config file

```ini
v
```

### Relevant log output

```shell
v
```

### Any other information that may be helpful

v

**Comment by mr-manuel** [comment]
Please read the issue form carefully and fill out all needed informations. Additionally I think your question would be better to be asked in the Victron Community.
