### ISSUE TITLE
Several web links in the section how to install do not work , this makes it all very confusing how to install 

### ISSUE THREAD

**Issue by merlep** [Louisvdw/dbus-serialbattery#887]
### Describe the problem

On webpage https://louisvdw.github.io/dbus-serialbattery/general/general/install#install-over-ssh  , under "Latest release " the link named "Install script " does not go to a valid location ( url https://louisvdw.github.io/dbus-serialbattery/general/general/install#install-over-ssh ) . Several other links on that page also do not work - makes it impossible to understand what the correct command is to install the latest release version

### Driver version

v1.00

### Venus OS device type

Cerbo GX

### Venus OS version

3.13

### BMS type

JKBMS / Heltec BMS

### Cell count

16

### Connection type

Serial USB adapter to RS485

### Config file

```ini
asd
```

### Relevant log output

```shell
we
```

### Any other information that may be helpful

sad

**Comment by mr-manuel** [comment]
Good question why. The links in the source code are correct. I have to take a deeper look.

**Comment by mr-manuel** [comment]
Unfortunately the error is still present. When building locally there is no issue.

**Comment by mr-manuel** [comment]
Found it. Problem fixed.
