### ISSUE TITLE
install via kwindrem SetupHelper

### ISSUE THREAD

**Issue by gchrisdu** [Louisvdw/dbus-serialbattery#920]
### Is your feature request related to a problem? Please describe.

dbus-serialbattery does not install via https://github.com/kwindrem/SetupHelper It would be nice to have it do so. I checked, and there is no archive in the proper location for SetupHelper to work, namely: 

https://github.com/Louisvdw/dbus-serialbattery/archive/latest.tar.gz  (when using 'latest' as the release tag in SetupHelper)

This archive exists for other packages that do work in their repos. with SetupHelper. Of course, there may be other reasons for it not to work, (script locations/existence,/function etc).

### Describe the solution you'd like

Be able to select your repo and release in SetupHelper and have it download and install dbus-serialbattery

### Describe alternatives you've considered

I can pull down the software and have it install locally.

### Additional context

You did provide the following comment a few years ago over on the victron community:

"I have not created a setup to work with SetupHelper. There is a ticket open to do that."

https://community.victronenergy.com/questions/76159/victron-venusos-driver-for-serial-connected-bms-av.html

Any updates? Thanks for this software, it is appreciated.

**Comment by mr-manuel** [comment]
See https://github.com/Louisvdw/dbus-serialbattery/issues/67.
