### ISSUE TITLE
Change static value of 24 cells in /Voltages and /Balances

### ISSUE THREAD

**Issue by CaptKrisp** [Louisvdw/dbus-serialbattery#93]
**Is your feature request related to a problem? Please describe.**
Not exactly.

**Describe the solution you'd like**
Modify code in dbushelper.py to use dynamic number of cells via 'self.battery.cell_count' instead of static 24 cells

**Describe alternatives you've considered**
In: setup_vedbus
        for i in range(self.battery.cell_count):
            self._dbusservice.add_path('/Voltages/Cell%s'%(str(i+1)), None, writeable=True, gettextcallback=lambda p, v: "{:0.3f}V".format(v))
            self._dbusservice.add_path('/Balances/Cell%s'%(str(i+1)), None, writeable=True)

-AND-
In: publish_dbus
        for i in range(self.battery.cell_count):
            voltage = self.battery.get_cell_voltage(i)
            self._dbusservice['/Voltages/Cell%s'%(str(i+1))] = voltage
            self._dbusservice['/Balances/Cell%s'%(str(i+1))] = self.battery.get_cell_balancing(i)

**Additional context**

**Comment by Louisvdw** [comment]
I think this is already done in the changes I commited from yesterday. 
Or is there a spot I missed?

**Comment by Louisvdw** [comment]
still need to look at making the qml display files more dynamic.
