### ISSUE TITLE
installation directory

### ISSUE THREAD

**Issue by ckvsoft** [Louisvdw/dbus-serialbattery#939]
### Is your feature request related to a problem? Please describe.

I would like to be able to specify a path during installation. It bothers me that it is installed in /data/etc. Don't understand why it doesn't install in /data like everyone else

etc is the central directory for all configuration files on Unix systems.

### Describe the solution you'd like

install to /data not to /data/etc

**Comment by mr-manuel** [comment]
We won‘t do that.

**Comment by ckvsoft** [comment]
OK, too bad. Then I have to install and customize it manually.
