### ISSUE TITLE
DalyBMS current fluctuating/jumping around

### ISSUE THREAD

**Issue by misterm15** [Louisvdw/dbus-serialbattery#991]
### Describe the problem

Hello,

i´ve one daly BMS (12S Li-Ion) running via Dbuserial on my CerboGX.
I see all data and everything seems to be fine.
One thing which i discover is a hughe fluctuating in current values compared to the charger or AC power values.
In attached picture you can see that the charger is more or less constanly or stable outputting a current while the bms jumps around.

Do you know if this is a known bug in dbusserial or is already the BMS data invalid / the issue?
![bms2](https://github.com/Louisvdw/dbus-serialbattery/assets/83763353/783c5b68-f218-4825-8f7c-a9f68bc9d272)

### Driver version

v1.0.2023053 

### Venus OS device type

Cerbo GX

### Venus OS version

3.14

### BMS type

Daly Smart BMS

### Cell count

12

### Battery count

1

### Connection type

Serial USB adapter to TTL

### Config file

```ini
BMS_TYPE = Daly
 INVERT_CURRENT_MEASUREMENT = -1
 MAX_BATTERY_CHARGE_CURRENT = 35.0
 MAX_BATTERY_DISCHARGE_CURRENT = 35.0
 MIN_CELL_VOLTAGE   = 3.40
 MAX_CELL_VOLTAGE   = 4.13
 FLOAT_CELL_VOLTAGE = 4.05
 CVCM_ENABLE = False
 BLOCK_ON_DISCONNECT = True
 LINEAR_LIMITATION_ENABLE = False
 CCCM_CV_ENABLE = False
 DCCM_CV_ENABLE = False
 CCCM_T_ENABLE = False
 DCCM_T_ENABLE = False
```

### Relevant log output

```shell
not needed
```

**Comment by mr-manuel** [comment]
I never saw a fluctiation caused by the driver. The driver only gets the data from the BMS and is not modified in this case for the current. As @rbeudel said, check directly on your BMS.
